### ISSUE TITLE
cordova-sqlite-storage and 1.0.0-beta.11

### ISSUE THREAD

**Issue by bitroost** [ionic-team/capacitor#1013]
After installing cordova-sqlite-storage, "npx cap update" fails when updating for android.

**Steps to reproduce:**

```
$ ionic start test blank --type=angular
$ cd test/
$ npm run build
$ npm install --save @capacitor/cli @capacitor/core
$ npx cap init test com.example.test
$ npx cap add android
$ npm install cordova-sqlite-storage --save
$ npx cap update
√ Updating Android plugins in 32.64ms
  Found 0 Capacitor plugins for android:
× update android: Cannot read property 'startsWith' of undefined
[error] Error running update: TypeError: Cannot read property 'startsWith' of undefined
    at Object.getFilePath (test\node_modules\@capacitor\cli\dist\plugin.js:127:29)
    at libFiles.map (test\node_modules\@capacitor\cli\dist\android\update.js:156:40)
    at Array.map (<anonymous>)
    at cordovaPlugins.map.p (test\node_modules\@capacitor\cli\dist\android\update.js:155:22)
    at Array.map (<anonymous>)
    at copyPluginsNativeFiles test\node_modules\@capacitor\cli\dist\android\update.js:131:20)
    at Object.updateAndroid (test\node_modules\@capacitor\cli\dist\android\update.js:25:9)
√ update web in 11.67μp
Update finished in 0.107s
```

**When going back to 1.0.0-beta.8 it works as expected:**

```
$ rm -R android
$ npm uninstall --save @capacitor/cli @capacitor/core @capacitor/android
$ npm uninstall cordova-sqlite-storage --save
$ npm install --save @capacitor/cli@1.0.0-beta.8 @capacitor/core@1.0.0-beta.8 @capacitor/android@1.0.0-beta.8
$ npx cap add android
$ npm install cordova-sqlite-storage --save
$ npx cap update
√ Updating Android plugins in 33.64ms
  Found 0 Capacitor plugins for android:
  Found 1 Cordova plugin for android
    CordovaSqliteStorage (2.5.2)
√ update android in 178.81ms
√ update web in 9.85μp
Update finished in 0.194s
```

**Comment by jcesarmobile** [comment]
Thanks for the very detailed issue.
I've followed the steps but it's working fine on my computer.
Are you testing on windows, mac or linux?
