### ISSUE TITLE
Error running update: Analyzing dependencies

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/capacitor#1072]
![Error Image](https://i.imgur.com/QzfmiPN.png "Pic of Terminal")

### Command

```
/usr/local/bin/pod install
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G4015)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ff9a4b5ace12e4ddd096d166acc28e96827c3d67
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '11.0'
use_frameworks!

target 'App' do
  # Add your Pods here

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsResources', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end
```

### Error

```
ArgumentError - Illformed requirement `""`
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/dependency.rb:115:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification/consumer.rb:210:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification/consumer.rb:210:in `block in dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification/consumer.rb:209:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification/consumer.rb:209:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification/consumer.rb:209:in `dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification.rb:336:in `block in dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification.rb:335:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification.rb:335:in `dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:36:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/abstract_external_source.rb:191:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/abstract_external_source.rb:191:in `validator_for_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/abstract_external_source.rb:178:in `validate_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/abstract_external_source.rb:173:in `store_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:697:in `fetch_external_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:673:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:671:in `fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:85:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

This is all the info I get running `npx cap update`. Any solutions?

**Comment by mariusbolik** [comment]
I deleted all `.podspec` Files in `ios/capacitor-cordova-ios-plugins/` and ran `npx cap update` again. 
Seems to work for now.

**Comment by mburger81** [comment]
I had the same issue but also this other line at the end:
`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

For me the solutions was doing
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

as described here https://github.com/nodejs/node-gyp/issues/569

**Comment by r0bertinski** [comment]
> sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

Thanks, it works for me!

**Comment by hidoos** [comment]
@mburger81 thx! it's works

**Comment by mesqueeb** [comment]
For anyone interested this seems to be the origin causing the issue:
https://stackoverflow.com/a/17980786/2697506
