### ISSUE TITLE
android:     java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by rizkyramadhan** [ionic-team/capacitor#1134]
Hi, i'm trying to open new window using 

```<a href="url" target="_blank">link</a>```

and then the app crashed with following log:

    java.lang.NullPointerException: Attempt to get length of null array
        at com.getcapacitor.Bridge.matchHosts(Bridge.java:828)
        at com.getcapacitor.Bridge.access$600(Bridge.java:75)
        at com.getcapacitor.Bridge$1.launchIntent(Bridge.java:219)
        at com.getcapacitor.Bridge$1.shouldOverrideUrlLoading(Bridge.java:210)
        at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:72)
        at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:163)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by jcesarmobile** [comment]
I fixed it the other day on this pr 
https://github.com/ionic-team/capacitor/pull/1128
