### ISSUE TITLE
capacitor sync issue

### ISSUE THREAD

**Issue by j3gb3rt** [ionic-team/capacitor#137]
Plugins: 
```
cordova-background-geolocation-lt 2.9.1 "BackgroundGeolocation"
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 3.7.2 "Diagnostic"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

Output:
```
✔ Copying web assets from www to android/app/src/main/assets/public in 1.31s
Updating platform android
✔ Fetching plugins in 394.68ms
[error] TypeError: Cannot read property 'filter' of undefined
    at getJSModules (/manhdev/tms-mobile-ui/node_modules/@capacitor/cli/dist/tasks/update.js:130:44)
    at plugins.map (/manhdev/tms-mobile-ui/node_modules/@capacitor/cli/dist/tasks/update.js:86:27)
    at Array.map (<anonymous>)
    at generateCordovaPluginsJSFile (/manhdev/tms-mobile-ui/node_modules/@capacitor/cli/dist/tasks/update.js:85:13)
    at Object.copyPluginsJS (/manhdev/tms-mobile-ui/node_modules/@capacitor/cli/dist/tasks/update.js:76:47)
    at Object.updateAndroid (/manhdev/tms-mobile-ui/node_modules/@capacitor/cli/dist/android/update.js:20:24)
    at <anonymous>
```

**Comment by j3gb3rt** [comment]
Only tested with android
