### ISSUE TITLE
Gettin the error message `not avaiable` when calling `PushNotifications.createChannel`

### ISSUE THREAD

**Issue by guilhermegjr** [ionic-team/capacitor#1563]
Description of the problem:

I am trying to create a Push Notification Channel and I am getting the error "not avaiable".

Affected platform
- [X] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [X] macOS
- [ ] linux

Other information:

Capacitor version: 6.9.0

node version: v10.14.1

npm version: 6.9.0

CocoaPods version: 1.7.0

Steps to reproduce:

1. Add the code bellow in `ngOnInit()` on `app.component.ts`: 

```typescript
PushNotifications.register();

PushNotifications.createChannel({
	id: 'PushPluginChannel',
	description: 'PushPluginChannel',
	importance: 5,
	visibility: 1,
	name: 'PushPluginChannel',
})
	.then(sucesso => console.log('sucess', sucess))
	.catch(erro => console.error('error', error));

PushNotifications.addListener('registration', token => {
	console.log(token);
});

PushNotifications.addListener('pushNotificationReceived', notification => {
	console.log(notification);
});

PushNotifications.addListener('registrationError', error => {
	console.log(error);
});

```

2. Build do app with `ng build`

3. npx cap copy

4. npx cap open android

5. Execute the app on real device

**Comment by jcesarmobile** [comment]
what's the Android version of the device? channels are only available on Android O and newer (SDK 26)

**Comment by guilhermegjr** [comment]
> what's the Android version of the device? channels are only available on Android O and newer (SDK 26)

I did know that. 

The android version I was using to try is the Nougat 7.0 (SDK 24).

Thanks for your answer.

**Comment by jpmc3630** [comment]
@jcesarmobile Is there anyway to get local notifications to the front without the channels? I was trying to support Android 7

**Comment by marshall86** [comment]
Hello, 

I'm having the same issue creating a new channel with capacitor 2.4.9 and Angular 11+

I tried on different devices and I even tried to change the min sdk version in the build.gradle but this is the error I get

 E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:542)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalArgumentException
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3646)
        at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:832)
        at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:820)
        at com.getcapacitor.plugin.notification.NotificationChannelManager.createChannel(NotificationChannelManager.java:89)
        at com.getcapacitor.plugin.notification.NotificationChannelManager.createChannel(NotificationChannelManager.java:57)
        at com.getcapacitor.plugin.PushNotifications.createChannel(PushNotifications.java:174)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:542) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:37)
        at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:796)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:3301)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:3322)
        at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1465)

FATAL EXCEPTION: CapacitorPlugins java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
 at com.getcapacitor.Bridge$1.run(Bridge.java:551)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:542)
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalArgumentException
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3646)
        at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:832)
        at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:820)
        at com.getcapacitor.plugin.notification.NotificationChannelManager.createChannel(NotificationChannelManager.java:89)
        at com.getcapacitor.plugin.notification.NotificationChannelManager.createChannel(NotificationChannelManager.java:57)
        at com.getcapacitor.plugin.PushNotifications.createChannel(PushNotifications.java:174)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:542) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:37)
        at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:796)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:3301)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:3322)
        at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1465)


Glad if you can help, thanks
