### ISSUE TITLE
[404] https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz

### ISSUE THREAD

**Issue by bhumin3i** [ionic-team/capacitor#1785]
i download project from git and used example repo for test.
Steps:
go to example dir
> cd example
> ../example$ npm install
  

**npm error log:**

```
> fsevents@1.1.3 install /Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
In file included from In file included from ../../nan/nan.h../../nan/nan.h::203203:
:
In file included from In file included from ../../nan/nan_new.h../../nan/nan_new.h::189189:
:
../../nan/nan_implementation_12_inl.h:337:28: ../../nan/nan_implementation_12_inl.hwarning: :337:28: warning: 'New' is deprecated'New'
       [-Wdeprecated-declarations]is 
deprecated
      [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();  return v8::StringObject::New(value).As<v8::StringObject>();

                           ^                           ^

/Users/rac/.node-gyp/10.13.0/include/node/v8.h:5052:3: note: 'New' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/rac/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
/Users/rac/.node-gyp/10.13.0/include/node/v8.h:5052:3: note: 'New' has been explicitly
      marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/rac/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:839:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:175:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:839:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:175:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
In file included from ../fsevents.cc:6:
../../nan/nan.h:854:18: warning: 'MakeCallback' is NODE_DEPRECATED("Use MakeCallback(..., async_context)",deprecated:
 Use ^MakeCallback(...,

      async_context) [-Wdeprecated-declarations]/Users/rac/.node-gyp/10.13.0/include/node/node.h
:91:20: note:     return node::MakeCallback(expanded
 from                 ^ 
macro
      'NODE_DEPRECATED'
/Users/rac/.node-gyp/10.13.0/include/node/node.h:168:1: note: 'MakeCallback' has been
          __attribute__((deprecated(message))) declaratorexplicitly
 marked                   ^ 
deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:854:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
In file included from ../fsevents.cc:6    return node::MakeCallback(:

                 ^../../nan/nan.h
/Users/rac/.node-gyp/10.13.0/include/node/node.h:168:1:: 869:18note::  'MakeCallback' warninghas:  been
'MakeCallback'       explicitlyis  markeddeprecated:  deprecatedUse  hereMakeCallback(...,

      async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
NODE_DEPRECATED("Use MakeCallback(..., async_context)",                 ^

^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:161/Users/rac/.node-gyp/10.13.0/include/node/node.h::191:: 20: note: note: 'MakeCallback' expandedhas  frombeen 
macro      
explicitly       'NODE_DEPRECATED'marked 
deprecated here
    __attribute__((deprecated(message))) declarator
                   ^
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:869:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:161:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:916:44: warning: 'ToString' is deprecated [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/rac/.node-gyp/10.13.0/include/node/v8.h:2454:10: note: 'ToString' has been
      explicitly marked deprecated here
In file included from ../fsevents.cc:6:
../../nan/nan.h:916:44: warning: 'ToString' is deprecated [-Wdeprecated-declarations]
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
      v8::Local<v8::String> string = from->ToString();
                                           ^/Users/rac/.node-gyp/10.13.0/include/node/v8config.h
:327:29:/Users/rac/.node-gyp/10.13.0/include/node/v8.h :2454:10:note : note: expanded 'ToString' fromhas  beenmacro
      
explicitly       marked'V8_DEPRECATED' deprecated 
here
  declarator __attribute__((deprecated))  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);

                            ^         ^

/Users/rac/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:926:27: warning: 'WriteUtf8' is deprecated In file included from [-Wdeprecated-declarations]../fsevents.cc:
6:
../../nan/nan.h:926:27: warning: 'WriteUtf8' is deprecated [-Wdeprecated-declarations]        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);

                          ^
/Users/rac/.node-gyp/10.13.0/include/node/v8.h:2658:3: note: 'WriteUtf8' has         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);been

                                ^explicitly
 marked deprecated here/Users/rac/.node-gyp/10.13.0/include/node/v8.h:
2658:3:   V8_DEPRECATED("Use Isolate* version",
  ^
note: 'WriteUtf8' has /Users/rac/.node-gyp/10.13.0/include/node/v8config.hbeen:
327      :explicitly29 :marked  deprecated herenote: 
expanded from macro
      'V8_DEPRECATED'
  V8_DEPRECATED("Use Isolate* version",
  ^
  declarator __attribute__((deprecated))/Users/rac/.node-gyp/10.13.0/include/node/v8config.h
:327:                            ^29
: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1478:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(...,
      async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:175:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
In file included from ^../fsevents.cc
:6:
../../nan/nan.h:1478:31:/Users/rac/.node-gyp/10.13.0/include/node/node.h :91warning:: 20:'MakeCallback'  is deprecated: noteUse:  MakeCallback(...,
      expandedasync_context)  from[-Wdeprecated-declarations] macro

      'NODE_DEPRECATED'
    return scope.Escape(node::MakeCallback(
                              ^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:175:1    __attribute__((deprecated(message))) declarator: 
note                   ^: 
'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/rac/.node-gyp/10.13.0/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
7 warnings generated.
7 warnings generated.
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp  SOLINK_MODULE(target) Release/fse.node
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.

> fsevents@1.2.9 install /Users/rac/Desktop/Projects/capacitor/example/node_modules/watchpack/node_modules/fsevents
> node install

ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.
  COPY /Users/rac/Desktop/Projects/capacitor/example/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/rac/Desktop/Projects/capacitor/example/node_modules/watchpack/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> node-sass@4.12.0 install /Users/rac/Desktop/Projects/capacitor/example/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/rac/.npm/node-sass/4.12.0/darwin-x64-64_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/rac/Desktop/Projects/capacitor/example/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.12.0 postinstall /Users/rac/Desktop/Projects/capacitor/example/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/rac/Desktop/Projects/capacitor/example/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by bhumin3i** [comment]
this is warning i solved

**Comment by SimonBrazell** [comment]
@bhumin3i how did you solve this? 

I'm experiencing the same issue now, looks like the resource at [https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz](https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz) is unavailable (404).

**Comment by bhandaribhumin** [comment]
@SimonBrazell actually use-v1....node is not required so don't worry about error.

**Comment by SimonBrazell** [comment]
@bhandaribhumin yeah never mind I was able to resolve the issue by removing some unnecessary dependencies in my `package.json`, removing `package-lock.json`, and reinstalling all dependencies.
