### ISSUE TITLE
Type error: Illegal Invocation on plugins addListener

### ISSUE THREAD

**Issue by LukaszGrela** [ionic-team/capacitor#1930]
Description of the problem:

Affected platform
- [x] Android

OS of the development machine
- [x] Windows

Other information:

Capacitor version:
1.2.0

node version:
8.13.0

npm version:
6.4.1

Steps to reproduce:
With the Capacitor 1.2.0 set some listeners to a plugin e.g. `backButton` or `networkStatusChange`. Build your project and update android app `npx cap copy`. 
Build Android app and run on the Android 5.1.1 emulator (API22). Notice in Logcat the `E/Capacitor/Console: File: https://localhost/ - Line 203 - Msg: TypeError: Illegal invocation` entries for each `addListener` on plugins.

You can also remotely debug the WebView chrome://inspect/#devices and in the console You will notice the error: 
>  TypeError: Illegal invocationmessage: "Illegal invocation"stack: "TypeError: Illegal invocation↵    at Object.capacitor.logToNative (http://localhost/:389:11)↵    at Object.toNative (http://localhost/:189:23)↵    at Object.capacitor.nativeCallback (http://localhost/:289:22)↵    at Object.capacitor.addListener (http://localhost/:305:32)↵    at Object.t.addListener (http://localhost/:857:22)↵    at Object.<anonymous> (http://localhost/static/js/main.794d4e58.chunk.js:1:993)↵    at a (http://localhost/:972:1111)↵    at Object.<anonymous> (http://localhost/static/js/main.794d4e58.chunk.js:1:226)↵    at a (http://localhost/:972:1111)↵    at c (http://localhost/:972:980)"get stack: function () { [native code] }set stack: function () { [native code] }__proto__: Errorlocalhost/:203 toNative

you can try to run following snippet in console which is also throwing the `TypeError: Illegal Invocation` error

```
Capacitor.Plugins.App.addListener('backButton', function(){console.log("back");});
```

**Note** to make the capacitor work on Android 5.1 you need to manually change line 70 of native-bridge.js to be:

```
  const consoleKeys = ["debug", "error", "info", "log", "warn", "dir", "dirxml", "table", "trace", "group", "groupCollapsed", "groupEnd", "clear", "count", "countReset", "assert", "profile", "profileEnd", "time", "timeLog", "timeEnd", "timeStamp", "context", "memory", "reactStack", "reactStackEnd"];
    // Object.keys(win.console)
    consoleKeys.forEach(function (level) {
```
Otherwise an error will be thrown and app will not load.

[Sample project](https://github.com/LukaszGrela/capacitor-android5.1-add-listener)

**Comment by LukaszGrela** [comment]
This errors comes from the `native-bridge.js` -> `postToNative(call)`. It is caused by the first use of the console method directly on the `orgConsole` object.

```
        var c = orgConsole;
        c.groupCollapsed('%cnative %c' + call.pluginId + '.' + call.methodName + ' (#' + call.callbackId + ')', 'font-weight: lighter; color: gray', 'font-weight: bold; color: #000');
        c.dir(call);
        c.groupEnd();
```

I was searching what could cause this error and I've found this [SO POST](https://stackoverflow.com/questions/9677985/uncaught-typeerror-illegal-invocation-in-chrome) which helped me to pinpoint the problem and apply solution.

Everywhere else the `orgConsole` method is accessed via `call` or `apply` but not in the `capacitor.logToNative` (nor in the `capacitor.logFromNative`). Adding a call and passing `win.console` as the context, fixed the problem.

I've changed previous snippet to be:

```
        var c = orgConsole;
        c.groupCollapsed.call(win.console,'%cnative %c' + call.pluginId + '.' + call.methodName + ' (#' + call.callbackId + ')', 'font-weight: lighter; color: gray', 'font-weight: bold; color: #000');
        c.dir.call(win.console,call);
        c.groupEnd.call(win.console);
```

And the error went away, and listeners started to work!
