### ISSUE TITLE
Capacitor Camera throwing "Unable to create photo on disk"

### ISSUE THREAD

**Issue by nj-coder** [ionic-team/capacitor#2013]
**Description of the problem:**
The camera plugin works great on Android 8+ devices, but for some reason, it throws the below error on a Samsung Tab A(SM-T280)
![image](https://user-images.githubusercontent.com/20697727/65921990-2f4ddc00-e427-11e9-92c4-6312eefca471.png)
**Affected platform**
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

**OS of the development machine**
- [x] Windows
- [ ] macOS
- [ ] linux

**Other information:**

Capacitor version: 1.2.1

node version: 10.16.3

npm version: 6.11.3

**Steps to reproduce:**

1. Configure the camera plugin as below on an Android 5 device
```
const image = await Plugins.Camera.getPhoto({
      quality: 100,
      allowEditing: false,
      resultType: CameraResultType.Base64,
      source: CameraSource.Camera
    });
```
2. Try opeing camera on the devices and check console for potential errors.

**Logcat**
```
10-01 12:42:20.799 20455-20642/com.uglunipart D/Capacitor/CameraUtils: Trying to save image to public external directory
10-01 12:42:50.288 20455-20642/com.uglunipart E/Capacitor/Plugin: Unable to create photo on disk
    java.io.IOException: open failed: ENOENT (No such file or directory)
        at java.io.File.createNewFile(File.java:944)
        at java.io.File.createTempFile(File.java:1009)
        at com.getcapacitor.plugin.camera.CameraUtils.createImageFile(CameraUtils.java:34)
        at com.getcapacitor.plugin.Camera.openCamera(Camera.java:199)
        at com.getcapacitor.plugin.Camera.showCamera(Camera.java:129)
        at com.getcapacitor.plugin.Camera.doShow(Camera.java:90)
        at com.getcapacitor.plugin.Camera.getPhoto(Camera.java:81)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$2.run(Bridge.java:529)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:937)
        at java.io.File.createTempFile(File.java:1009) 
        at com.getcapacitor.plugin.camera.CameraUtils.createImageFile(CameraUtils.java:34) 
        at com.getcapacitor.plugin.Camera.openCamera(Camera.java:199) 
        at com.getcapacitor.plugin.Camera.showCamera(Camera.java:129) 
        at com.getcapacitor.plugin.Camera.doShow(Camera.java:90) 
        at com.getcapacitor.plugin.Camera.getPhoto(Camera.java:81) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$2.run(Bridge.java:529) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
10-01 12:42:50.288 20455-20642/com.uglunipart D/Capacitor: Sending plugin error: {"save":false,"callbackId":"22237336","pluginId":"Camera","methodName":"getPhoto","success":false,"error":{"message":"Unable to create photo on disk"}}
10-01 12:42:50.308 20455-20455/com.uglunipart E/Capacitor/Console: File: http://localhost/main-es2015.a5ca47b02acd21cd4cd6.js - Line 1 - Msg: ERROR Error: Uncaught (in promise): Object: {"message":"Unable to create photo on disk"}
```

**Comment by nj-coder** [comment]
**UPDATE:** issue happens only when `saveToGallery `is set to `true`

**Comment by yigitbacakoglu** [comment]
Error still continues in the latest versions, any update?

**Comment by Xdabier** [comment]
> Error still continues in the latest versions, any update?

Same here running on: {
"@capacitor/cli": "2.3.0",
"@angular/cli": "~9.1.5",
"@capacitor/android": "^2.3.0",
    "@capacitor/core": "2.3.0",
"@ionic/angular": "^5.0.0",

}

**Comment by matthewdenobrega** [comment]
I'm getting the same error on Android, and setting saveToGallery to false does not resolve it. After upgrading Capacitor / Ionic recently:
"@capacitor/android": "2.1.2",
"@capacitor/core": "2.1.2",
"@ionic-native/core": "5.14.0",
"@ionic/angular": "5.3.1",

**Comment by danielzen** [comment]
Still seeing this on     `"@capacitor/android": "^2.4.7",`

**Comment by hembachrterran** [comment]
What's the solution to this error? Still exists with `"@capacitor/core": "^2.4.0"` and `"@capacitor/android": "^2.4.7"`.

**Comment by mtpultz** [comment]
@hembachrterran were you able to resolve this issue?  I have this issue now in our Ionic 5 application using the same version as you are.

**Comment by hembachrterran** [comment]
As I remember this problem was solved by ask CAMERA permission in app.component.ts:
```
constructor(public androidPermissions:AndroidPermissions)
{
this.androidPermissions.requestPermissions([
      this.androidPermissions.PERMISSION.CAMERA,
      this.androidPermissions.PERMISSION.READ_EXTERNAL_STORAGE,
      this.androidPermissions.PERMISSION.WRITE_EXTERNAL_STORAGE,]);
```
and you have to add android:requestLegacyExternalStorage="true" and
```
<!-- Camera, Photos, input file -->
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.CAMERA" />
```
to AndroidManifest.xml.

Pay attention to the target Android version in your app, after Android 10 (API level 29) was a storage update in Android, and you can not use the requestLegacyExternalStorage variable with higher target level, more info:
https://developer.android.com/about/versions/11/privacy/storage

**Comment by ImAbhishekTomar** [comment]
@hembachrterran  - I have tried but after adding this app is causing below issue.

```
Error binding to custom tabs service
2022-10-13 16:18:13.338 23072-23072 Capacitor/Console       com.cam.abc                    E  File: http://192.168.1.8:8100/vendor.js - Line 70953 - Msg: ERROR NullInjectorError: R3InjectorError(AppModule)[AndroidPermissions -> AndroidPermissions -> AndroidPermissions]: 
NullInjectorError: No provider for AndroidPermissions!
```
