### ISSUE TITLE
bug: sidemenu not open on Android 5.0/5.1

### ISSUE THREAD

**Issue by rmalca** [ionic-team/capacitor#2030]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.2.1

  @capacitor/core 1.2.1

  @capacitor/android 1.2.1


[success] Android looking great!
```

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
On start sidemenu example the sidemenu not open on Android 5.0/5.1.

## Reproduction Steps

1. Create ionic capacitor project: `ionic start myApp sidemenu --capacitor`
2. Add android platform and run with Android Studio on Android 5 AVD.

## Other Technical Details

`npm --version` output: 6.11.3

`node --version` output: v12.11.1

`ionic --version` output: 5.4.2

## Other Information

Console output:
```
The key "viewport-fit" is not recognized and ignored. VM20:979
Ionic Native: deviceready event fired after 1089 ms bootstrap.js:12
Angular is running in the development mode. Call enableProdMode() to enable the production mode. core.js:38780
Native: tried calling StatusBar.styleDefault, but the StatusBar plugin is not installed. common.js:267
Install the StatusBar plugin: 'ionic cordova plugin add cordova-plugin-statusbar' common.js:279
Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed. common.js:267
Install the SplashScreen plugin: 'ionic cordova plugin add cordova-plugin-splashscreen' common.js:279
Unhandled Promise rejection: Cannot read property 'call' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError TypeError: Cannot read property 'call' of undefined
    at Object.toNative (http://localhost/:204:23)
    at Object.capacitor.nativeCallback (http://localhost/:290:22)
    at Object.capacitor.addListener (http://localhost/:306:32)
    at Object.t.addListener (http://localhost/:909:22)
    at HTMLDocument.document.addEventListener (http://localhost/:131:56)
    at Object.startHardwareBackButton (http://localhost/hardware-back-button-5afe3cb0-js-es5.js:29:11)
    at http://localhost/6-es5.js:176:33
    at ZoneDelegate.invoke (http://localhost/polyfills-es5.js:16655:164)
    at Zone.run (http://localhost/polyfills-es5.js:16316:41)
    at http://localhost/polyfills-es5.js:17301:30 
```

package.json
```
{
  "name": "myApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@capacitor/android": "^1.2.1",
    "@capacitor/core": "1.2.1",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@capacitor/cli": "1.2.1",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project"
}
```

**Comment by jcesarmobile** [comment]
The `Cannot read property 'call' of undefined` should be fixed here https://github.com/ionic-team/capacitor/pull/1991

Android 5 emulators have a very old chrome version that can't be updated, so some features might not work well there. In any case, you should report that on the Ionic repo as that's what creates the menu.

Capacitor requires Chrome/Chromium version 50 or later, so test on real devices where the SystemWebView/Chrome is up to date https://capacitor.ionicframework.com/docs/getting-started/dependencies#android-development
