### ISSUE TITLE
bug: Unable to Run after Build (Splash$2.run)  

### ISSUE THREAD

**Issue by frabaddo** [ionic-team/capacitor#2075]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
 ```
Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.2.1

  @capacitor/core 1.2.1

  @capacitor/android 1.2.1


[success] Android looking great!
 ```
## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Fresh conversion from cordova to capacitor. After building, on launching the app I get the following log error than the app crashes.
 ```
D/Capacitor: App resumed
D/OpenGLRenderer: Skia GL Pipeline
D/Capacitor: Handling local request: http://localhost/
D/Capacitor: Handling local request: http://localhost/
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ******, PID: 1451
    java.lang.IllegalStateException: View android.widget.ImageView{35033b3 V.ED..... ......ID 0,0-0,0} has already been added to the window manager.
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:328)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at com.getcapacitor.Splash$2.run(Splash.java:236)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process: Sending signal. PID: 1451 SIG: 9
Process 1451 terminated.

```
## Expected Behavior
I want to be able to use app after building

## Other Technical Details

`npm --version` output: 5.6.0

`node --version` output: v8.11.3

## Other Information

Not tested on IOS

**Comment by jcesarmobile** [comment]
can you provide your package.json or list of cordova plugins?

**Comment by frabaddo** [comment]
My bad, the error was caused by a typo in MainActivity. I've inserted Teo time the init function
