### ISSUE TITLE
How to use electron builder

### ISSUE THREAD

**Issue by laclance** [ionic-team/capacitor#2223]
I create a new app with `ionic start myApp blank --capacitor --type=react`
then create an electron app and run electron-builder:
`ionic build`
`npx cap init --web-dir=build`
`npx cap add electron`
`cd electron && npm i -D electron-builder`
`node ./node_modules/.bin/electron-builder`

And i get the following output: 
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

Am i missing something? I have tried from root directory (not /electron)
running windows 10 
node 8.16.2
ionic 5.4.6
capacitor 1.3.0
electron-builder 21.2.0

**Comment by laclance** [comment]
The error was from running `node node_modules\.bin\electron-builder`. Adding electron-builder to an npm script worked.
