### ISSUE TITLE
bug: com.darryncampbell.cordova.plugin.intent chrashes app

### ISSUE THREAD

**Issue by keo9ren** [ionic-team/capacitor#2528]
# Bug Report

## Capacitor Version
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 1.5.0

  @capacitor/core: 1.5.0

  @capacitor/android: 1.5.0

  @capacitor/ios: 1.5.0

Installed Dependencies:

  @capacitor/ios not installed

  @capacitor/cli 1.5.0

  @capacitor/android 1.5.0

  @capacitor/core 1.5.0

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
App Chrashed at boot.

## Expected Behavior
App starts normally
## Sample Code or Sample Application Repo
None
## Reproduction Steps

Add cordova plugin com-darryncampbell-cordova-plugin-intent in Version 1.3.0 to your android app.

App crashes durint startup. See exception from Logcat below.

## Other Technical Details
2020-03-05 14:18:03.336 28247-28247/com.app.identifier/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.identifier, PID: 28247
    java.lang.RuntimeException: Unable to instantiate application com.darryncampbell.cordova.plugin.intent.CordovaPluginIntentFileProvider: java.lang.ClassCastException: com.darryncampbell.cordova.plugin.intent.CordovaPluginIntentFileProvider cannot be cast to android.app.Application
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1138)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6298)
        at android.app.ActivityThread.access$1200(ActivityThread.java:242)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7179)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.ClassCastException: com.darryncampbell.cordova.plugin.intent.CordovaPluginIntentFileProvider cannot be cast to android.app.Application
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at android.support.v4.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:49)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1124)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1130)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6298) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:242) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7179) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by jcesarmobile** [comment]
I can't reproduce with latest @capacitor/cli and @capacitor/android (2.0.0-beta.0) and latest plugin (2.0.0)
Try updating with
```
npm install @capacitorc/cli@next
npm install @capacitor/core@next
npm install @capacitorc/android@next
npm install com-darryncampbell-cordova-plugin-intent@latest
npx cap sync android
```
and see update guide for some required changes
https://capacitor.ionicframework.com/docs/android/updating/#from-1-5-1-to-2-0-0-beta-0

If you still face the issue, create a new issue providing more information (sample app, Android version where the issue manifest, etc)
