### ISSUE TITLE
bug: Cannot edit album Image using Camera plugin when selecting a photo

### ISSUE THREAD

**Issue by maaljam** [ionic-team/capacitor#2695]
# Bug Report

## Capacitor Version
`npx cap doctor` output:
 @capacitor/electron not installed
  @capacitor/cli 2.0.0
  @capacitor/core 2.0.0
  @capacitor/android 2.0.0

## Affected Platform(s)

- [X] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
When calling `getPhoto` with `allowEditing: true`, editing a photo only works with 'Take Picture' option but does not work when you select an image from phone album via 'From Photos' option. As soon as you select a picture, Camera Plugin returns an error `Unable to edit image'

## Expected Behavior
When a pic is selected from album, the photo should appear in the chosen editing app (official android photos app in my case) to be edited instead of terminating the process and taking the user back to the app with the error mentioned above.

## Sample Code or Sample Application Repo

````
async onButtonClick() {
	const image = await Camera.getPhoto({
		quality: 90,
		allowEditing: true,
		resultType: CameraResultType.Uri,
	});
}

````

## Reproduction Steps

1- call `Camera.getPhoto` with `allowEditing: true`
2- choose 'From Photos'
3- select an image
4- error will be returned (using chrome remote debugger)

Note: the test was conducted on a real device not a simulator

## Other Technical Details

`npm --version` output:6.1.0

`node --version` output: v10.0.0

`pod --version` output (iOS issues only):

## Other Information

I tried to get some info about the error in Camera.java with few break points. Here is the output of both catch exceptions:

line 501: `catch (SecurityException ex)` : `UID 10437 does not have permission to content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F359216/ORIGINAL/NONE/image%2Fjpeg/996445689 [user 0]`

line 509:`catch (Exception ex) {` : `Failed to find configured root that contains /data/data/com.XXX.YYYY/cache/363091782.1586033656904.jpeg`

**Comment by jcesarmobile** [comment]
I forgot to document this change in the template
https://github.com/ionic-team/capacitor/pull/2671/files#diff-da11a74f89b28e0bd255c0c39963a2d7R4

**Comment by snow-drop** [comment]
@jcesarmobile I've followed this [updating.md](https://github.com/jcesarmobile/capacitor/blob/816217bb02017728f5c05d295e60f2600d350222/site/docs-md/android/updating.md) especially the part in the `FileProvider` section but I'm still getting the same error in my Android 9 tab.

My config is as follows: 
```
const options = {
    allowEditing: true,
    quality: 25,
    resultType: CameraResultType.Uri,
    source: CameraSource.Photos,
    saveToGallery: true
}
```

and I use it like this:
```
 const image = await Camera.getPhoto(options)
```

And the stack trace in Android Studio is as follows:
```
E/Capacitor/Plugin: Unable to edit image
    android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/Screenshots/Screenshot_2021-01-01-13-07-41-068~2.png exposed beyond app through Intent.getData()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
        at android.net.Uri.checkFileUriExposed(Uri.java:2371)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10247)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10201)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1667)
        at android.app.Activity.startActivityForResult(Activity.java:4659)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:4617)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at com.getcapacitor.Bridge.startActivityForPluginWithResult(Bridge.java:733)
        at com.getcapacitor.Plugin.startActivityForResult(Plugin.java:546)
        at com.getcapacitor.plugin.Camera.editImage(Camera.java:493)
        at com.getcapacitor.plugin.Camera.returnResult(Camera.java:336)
        at com.getcapacitor.plugin.Camera.processPickedImage(Camera.java:273)
        at com.getcapacitor.plugin.Camera.handleOnActivityResult(Camera.java:473)
        at com.getcapacitor.Bridge.onActivityResult(Bridge.java:786)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:209)
        at android.app.Activity.dispatchActivityResult(Activity.java:7527)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4384)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4433)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

Running `npx cap doctor`:
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.5
  @capacitor/core: 2.4.5
  @capacitor/android: 2.4.5
  @capacitor/electron: 2.4.5
  @capacitor/ios: 2.4.5

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.5
  @capacitor/core 2.4.5
  @capacitor/android 2.4.5
  @capacitor/electron not installed

```

**Comment by adeldx** [comment]
up...
Same issue on Android 11 with the latest update.

**Comment by codeeshop-oc** [comment]
facing same issue with Android 9

**Comment by ivanov84** [comment]
Exmplanation here:
https://github.com/ionic-team/capacitor/issues/3246#issuecomment-797557197
