### ISSUE TITLE
bug:Local Notifications--- Notifications not enabled on this device

### ISSUE THREAD

**Issue by qqaimh** [ionic-team/capacitor#2710]
# Bug Report

## Capacitor Version

Capacitor Version:2.0 And 1.5 are same.
`npx cap doctor` output:
NO Problem

## Affected Platform(s)

- [1 ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 111430489, pluginId: LocalNotifications, methodName: areEnabled
V/Capacitor: callback: 111430489, pluginId: LocalNotifications, methodName: areEnabled, methodData: {}
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 111430490, pluginId: LocalNotifications, methodName: schedule
V/Capacitor: callback: 111430490, pluginId: LocalNotifications, methodName: schedule, methodData: {"notifications":[{"body":"This is a fine SkekNot","id":1,"title":"Skekification!","sound":null,"schedule":{"repeats":true,"every":"second","count":10}}]}
D/Capacitor: Sending plugin error: {"save":false,"callbackId":"111430490","pluginId":"LocalNotifications","methodName":"schedule","success":false,"error":{"message":"Notifications not enabled on this device"}}
E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:520)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference
        at com.getcapacitor.plugin.LocalNotifications.schedule(LocalNotifications.java:79)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:520) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.example.app, PID: 1099
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge$1.run(Bridge.java:529)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:520)
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference
        at com.getcapacitor.plugin.LocalNotifications.schedule(LocalNotifications.java:79)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:520) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
E/Capacitor/Console: File: http://localhost/main-es5.6ea357cb770a27bd4e8a.js - Line 1 - Msg: ERROR
I/Process: Sending signal. PID: 1099 SIG: 9

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

**Comment by qqaimh** [comment]
> Can you provide a sample app?
In Tab2
https://github.com/qqaimh/myapp5

**Comment by qqaimh** [comment]
> Can you provide a sample app?

I try it in three android mobile. But only one can use Local Notifications.

**Comment by jcesarmobile** [comment]
I can't reproduce
what's the Android version of the devices that crash?
what do you get if you type `navigator.userAgent` in chrome inspector?

**Comment by jcesarmobile** [comment]
I could reproduce, it crash if the notifications are disabled

**Comment by qqaimh** [comment]
> I could reproduce, it crash if the notifications are disabled

How to enable notifications if the notifications  of mobile are disabled

**Comment by jcesarmobile** [comment]
In settings app, there is an "apps and notifications" screen, you should see your app there and enable the notifications for it

**Comment by qqaimh** [comment]
> In settings app, there is an "apps and notifications" screen, you should see your app there and enable the notifications for it

Thank you. I find it and now it is ok
