### ISSUE TITLE
bug: Filesystem.stat() crashes app

### ISSUE THREAD

**Issue by ThomasKientz** [ionic-team/capacitor#2846]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

> ```
>   @capacitor/cli 2.0.1
>   @capacitor/core 2.0.1
>   @capacitor/android 2.0.1
> ```

## Affected Platform(s)

- [ ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Description

```
const data = await Filesystem.readFile({
  path,
})
const { size } = await Filesystem.stat({
  path,
})

```
No issues with `Filesystem.readFile`

With  `Filesystem.stat` the app crashed and I got the following error in the Android Studio console

```
2020-04-29 17:06:28.150 6188-6388/com.boomerang.app V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 77806689, pluginId: Filesystem, methodName: stat
2020-04-29 17:06:28.150 6188-6388/com.boomerang.app V/Capacitor: callback: 77806689, pluginId: Filesystem, methodName: stat, methodData: {"path":"content:\/\/com.android.providers.media.documents\/document\/image%3A24"}
2020-04-29 17:06:28.152 6188-6340/com.boomerang.app E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:520)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at com.getcapacitor.plugin.Filesystem.getDirectory(Filesystem.java:67)
        at com.getcapacitor.plugin.Filesystem.getFileObject(Filesystem.java:90)
        at com.getcapacitor.plugin.Filesystem.stat(Filesystem.java:440)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:520) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2020-04-29 17:06:28.153 6188-6340/com.boomerang.app E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.boomerang.app, PID: 6188
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge$1.run(Bridge.java:529)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:520)
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at com.getcapacitor.plugin.Filesystem.getDirectory(Filesystem.java:67)
        at com.getcapacitor.plugin.Filesystem.getFileObject(Filesystem.java:90)
        at com.getcapacitor.plugin.Filesystem.stat(Filesystem.java:440)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:520) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by ThomasKientz** [comment]
@jcesarmobile I made further tests. Crash only occurs with paths starting `content://`. I got those paths from an intent (https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent#intentshimonintent)

Here is a sample app : 
https://github.com/ThomasKientz/capacitor-fs-issue-repro

**Comment by jcesarmobile** [comment]
Yeah, content urls are only supported by readFile at the moment because they are not regular filesystem url, they belong to other app, so most Filesystem functions won't work on them, only readFile and maybe stat could be implemented with a lot of content resolver code. But should definitely not crash.

**Comment by tobiasmuecksch** [comment]
Same issue with the `copyFile` method.

**Comment by jcesarmobile** [comment]
This issue is about content urls, that's an android thing, so can't work on iOS.
If you mean copyFile doesn't work on Android, report a new issue and provide more information.

**Comment by tobiasmuecksch** [comment]
What I mean is, that `Filesystem.copy()`doesn't work with `content://` urls too. This issue doesn't only effect the `stat` method.
My iOS comment is about my expectation, that I can use the same code for android and iOS. That means pass in a Filesystem URI which I got by some plugin and the Filesystem plugin just does it's magic as it is supposed too. But as often, I have to provide some extra code for Android.... As far as I can tell, in order to copy over a file from a `content://` URI I'd have to read the file as base64 and then write it to the `data`-directory for example. That is tremendous overhead. Is there any other way?

**Comment by tobiasmuecksch** [comment]
I think important information like that, should be displayed way more prominent in the docs. The current hint

> Additionally, the Filesystem API supports using full file:// paths, or reading content:// files on Android. Simply leave out the directory param to use a full file path.

is not sufficiently clear at all.

**Comment by tobiasmuecksch** [comment]
I found a solution / workaround.

I'm now converting `content://` URLs to `file://` with the following plugin:

https://ionicframework.com/docs/native/file-path
