### ISSUE TITLE
bug: Push Notification crashes with IllegalStateException

### ISSUE THREAD

**Issue by trytuna** [ionic-team/capacitor#3308]
### Capacitor Version
```
% npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.3.0
  @capacitor/core: 2.3.0
  @capacitor/android: 2.3.0
  @capacitor/electron: 2.3.0
  @capacitor/ios: 2.3.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.3.0
  @capacitor/core 2.3.0
  @capacitor/android 2.3.0
  @capacitor/electron not installed

[success] Android looking great! 👌
```

### Platform(s)
android

### Current Behavior
I am setting up Push Notification in the app.component.ts with the `PushNotifications.register()` function. This causes the android App to crash with the following Stacktrace.

```
E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:521)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process io.ionic.starter. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.3.0:184)
        at com.google.firebase.messaging.FirebaseMessaging.getInstance(com.google.firebase:firebase-messaging@@20.1.2:1)
        at com.getcapacitor.plugin.PushNotifications.register(PushNotifications.java:82)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:521) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

### Code Reproduction
I build a sample project to reproduce that issue. Note that this is not the project I initially face that problem. We are using the PushNotification plugin for a while in production and just recently (after updating to the latest capacitor version) got this bug.

https://github.com/trytuna/capacitor-push-notification-bug

**Comment by jcesarmobile** [comment]
Your sample app doesn't have the `google-services.json` file, do you have it inside `android/app folder`?

**Comment by trytuna** [comment]
Wow, now I am embarrassed. Thats was the actual problem. Ufff, I have to do that more often I guess :D. I am closing this Issue. Sorry for wasting your time
