### ISSUE TITLE
 error. while running npm i -D -E @capacitor/cli

### ISSUE THREAD

**Issue by ibnjunaid** [ionic-team/capacitor#3360]
### Capacitor Version

```
Im getting the following error. while running npm i -D -E @capacitor/cli

npm verb stack SyntaxError: Unexpected end of JSON input while parsing near '...FCnINK8IxATDi2WfhWMRD'
npm verb stack     at JSON.parse (<anonymous>)
npm verb stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Platform(s)
Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

### Current Behavior
Unable to install capacitor

### Expected Behavior
Expected behaviour is to install @capacitor/cli on my machine

`npm --version` output: 6.13.0

`node --version` output: 12.12.0

`pod --version` output (iOS issues only):

**Comment by ibnjunaid** [comment]
Apparently i was running into trouble because of npm cache.
 For me It worked, After i ran `npm cache clean --force`.
