### ISSUE TITLE
bug: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abc/com.abc.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void j.a.a.g.a(java.lang.String, j.a.a.e, j.a.a.j, j.a.a.h)'

### ISSUE THREAD

**Issue by kishan-coditas** [ionic-team/capacitor#3432]
## Bug Report
I am not able to open release APK. Debug apk works just fine. Error is something Like this...

```
2020-08-18 20:58:49.617 10888-10888/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abc, PID: 10888
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abc/com.abc.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void j.a.a.g.a(java.lang.String, j.a.a.e, j.a.a.j, j.a.a.h)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void j.a.a.g.a(java.lang.String, j.a.a.e, j.a.a.j, j.a.a.h)' on a null object reference
        at j.a.a.o.a(Unknown Source:42)
        at j.a.a.o.e(Unknown Source:28)
        at j.a.a.o.a(Unknown Source:22)
        at com.getcapacitor.e0.c.a(Unknown Source:54)
        at com.getcapacitor.c.a(Unknown Source:46)
        at com.getcapacitor.c.a(Unknown Source:59)
        at com.getcapacitor.c.a(Unknown Source:1)
        atcom.abc.MainActivity.onCreate(Unknown Source:8)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 

```
### Capacitor Version
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/core 2.2.1
  @capacitor/android 2.2.0
  @capacitor/cli 2.2.1
  @capacitor/electron not installed

[success] Android looking great! 

```
PASTE OUTPUT HERE
```

### Platform(s)
android

### Current Behavior
Release APK is crashing

### Expected Behavior
Not able to start release apk

### Other Technical Details

`npm --version` output:
6.9.0
`node --version` output:
v10.16.3

**Comment by jcesarmobile** [comment]
did you change minifyEnabled to true for release? that could probably cause this kind of issues

**Comment by kishan-coditas** [comment]
Yeah, actually that helps. But still not able to understand why I need to disabled that ?

**Comment by jcesarmobile** [comment]
It's a know problem, probably related to the reflection used in plugins 
Closing as there is another issue already https://github.com/ionic-team/capacitor/issues/739
Last comment has some rules that can be used to make it work (but I didn't personally try)
