### ISSUE TITLE
Android app crashing on startup

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#385]
Hi.

Just set up the PC with Java 8, Android SDK, Java JDK, Android Studio. 

Added Capacitor to my Vue.js-project. Added platforms for iOS and Android. 

- I managed to build and run the app on a mac with an iPhone 8 connected to it. It worked flawlessly.

- I manage to build my Android-app without warnings or errors. After the app is put on my connected device and is opened it immediately crashes. Trying to run it again by opening the app directly in the device it crashes. I only see the splash-screen for a second or so.

Any ideas?

From logcat:

```
03-27 14:37:05.410 20524-20524/com.lakemedelsappen.app E/Capacitor: Unable to read file at path public/plugins
03-27 14:37:05.413 20524-20524/com.lakemedelsappen.app D/Capacitor: Loading app at https://abf5285c-235b-4fa1-943e-542f9ff23539capacitorapp.net
03-27 14:37:05.420 20524-20567/com.lakemedelsappen.app W/cr_media: Requires BLUETOOTH permission
03-27 14:37:05.428 20524-20580/com.lakemedelsappen.app E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
03-27 14:37:05.432 20524-20559/com.lakemedelsappen.app D/SERVER: Handling local request: https://abf5285c-235b-4fa1-943e-542f9ff23539capacitorapp.net/
03-27 14:37:05.432 20524-20524/com.lakemedelsappen.app D/AndroidRuntime: Shutting down VM

    --------- beginning of crash
03-27 14:37:05.432 20524-20524/com.lakemedelsappen.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lakemedelsappen.app, PID: 20524
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lakemedelsappen.app/com.lakemedelsappen.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject org.json.JSONObject.getJSONObject(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3003)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject org.json.JSONObject.getJSONObject(java.lang.String)' on a null object reference
        at com.getcapacitor.Plugin.getConfigValue(Plugin.java:134)
        at com.getcapacitor.Splash.showOnLaunch(Splash.java:74)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:76)
        at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:54)
        at com.lakemedelsappen.app.MainActivity.onCreate(MainActivity.java:16)
        at android.app.Activity.performCreate(Activity.java:6977)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064) 
        at android.app.ActivityThread.-wrap14(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6823) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451) 
```

**Comment by mlynch** [comment]
Thanks, should be fixed here in the next release today. Cheers

**Comment by solojuve1897** [comment]
Oh thanx :-)

**Comment by mlynch** [comment]
Should be fixed in alpha.30 which just went out, can you try updating and let me know if it works?

```
npm install @capacitor/android@latest
npx cap update
```

**Comment by jcesarmobile** [comment]
Try adding this to your capacitor.config.json

```
"plugins": {
    "SplashScreen": {
      "launchShowDuration": 12345
    }
  }
```

**Comment by mlynch** [comment]
Fixed the issue in master, will have it released later today

**Comment by solojuve1897** [comment]
@mlynch Finally it's alive and kicking. Thanx for the help. Was about to go mad there for a bit.

**Comment by mlynch** [comment]
w00t! Glad the update was easy too, seems we've got that working well 👯
