### ISSUE TITLE
bug: Camera.getPhoto causes error Volume external_primary not found

### ISSUE THREAD

**Issue by ihsanberahim** [ionic-team/capacitor#3889]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.4
  @capacitor/core: 2.4.4
  @capacitor/android: 2.4.4        
  @capacitor/electron: 2.4.4       
  @capacitor/ios: 2.4.4

Installed Dependencies:

  @capacitor/cli 2.4.4
  @capacitor/core 2.4.4
  @capacitor/android 2.4.3
  @capacitor/ios 2.4.3
```

### Platform(s)

android

### Current Behavior

trigger `Camera.getPhoto` causes error below, after pick an image

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9003, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/29/ORIGINAL/NONE/image/jpeg/665145974 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F29/ORIGINAL/NONE/image%2Fjpeg/665145974} }} to activity {com.tactlink.app/com.tactlink.app.MainActivity}: java.lang.IllegalArgumentException: Volume external_primary not found
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Volume external_primary not found
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1687)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
        at com.getcapacitor.plugin.Camera.processPickedImage(Camera.java:266)
        at com.getcapacitor.plugin.Camera.handleOnActivityResult(Camera.java:499)
        at com.getcapacitor.Bridge.onActivityResult(Bridge.java:776)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:214)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

### Expected Behavior

Expected not crash

### Code Reproduction

```
const { Camera } = Plugins;
const cameraPhoto = await Camera.getPhoto({
    quality: 90,
    width: 600,
    allowEditing: false,
    resultType: CameraResultType.DataUrl,
    source: CameraSource.Photos
});
```

### Other Technical Details

`npm --version` output: 6.14.4

`node --version` output: v12.18.0

`pod --version` output (iOS issues only):

### Additional Context

https://stackoverflow.com/a/63172433/2342289

**Comment by ihsanberahim** [comment]
Oh, seems Android emulator problem. My problem solved after wipe the emulator data based on this answer.
https://github.com/akshay2211/PixImagePicker/issues/103#issuecomment-694832401
