### ISSUE TITLE
cordova-plugin-googleplus Can only use the lower 16 bits for requestCode

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/capacitor#405]
Trying to get Native Google auth working in capacitor and getting this error. I am using stencil 7.7 and no framework.

**Comment by mlynch** [comment]
Do you have a stack trace or more info? Thanks.

**Comment by popcorn245** [comment]
Yes, I was on my mobile sorry for the brevity.

```
D/Capacitor: Firing change: true
             Notifying listeners for event appStateChange
             No listeners found for event appStateChange
D/Capacitor: App resumed
D/Capacitor: Notifying listeners for event networkStatusChange
             No listeners found for event networkStatusChange
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@9a638c time:92857557
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@34ca091
D/Capacitor: To native (Cordova): GooglePlus302150710, service: GooglePlus, action: login, actionArgs: [{"webClientId":"<Key was here>","offline":true}]
I/GooglePlugin: Building Google options
I/GooglePlugin: Building GoogleApiClient
I/GooglePlugin: GoogleApiClient built
I/GooglePlugin: Trying to Log in!
E/PluginManager: Uncaught exception from plugin
                 java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
                     at android.support.v4.app.BaseFragmentActivityApi14.checkForValidRequestCode(BaseFragmentActivityApi14.java:79)
                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:717)
                     at nl.xservices.plugins.GooglePlus.signIn(GooglePlus.java:197)
                     at nl.xservices.plugins.GooglePlus.execute(GooglePlus.java:93)
                     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
                     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
                     at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
                     at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:71)
                     at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
                     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loop(Looper.java:159)
                     at android.os.HandlerThread.run(HandlerThread.java:61)
```

## Environment Info
Cap Version: 1.0.0-alpha.30
Stack: StencilJS
Java: 1.8.0_161

## Notes
I didn't use ionic/native as it was giving me errors so I am just using the cordova plugin directly.

**Comment by jcesarmobile** [comment]
This is a limitation of BridgeActivity, which extends AppCompatActivity, which extends FragmentActivity.
Fragments have a limitation of 16bit for the integer used as request code (max is 32767), while a regular Cordova app uses a regular Activity, in which the limitation is 32bit for the integer.
I don't think we can easily change BridgeActivity to extend Activity instead of AppCompatActivity.

This also affects phonegap-plugin-barcodescanner.
So we should probably send PRs to some plugins to make the request code smaller. We don't need to say that it's because of Capacitor as this also affects apps that embed Cordova if they use a Fragment instead of an Activity, which is most common this days.

**Comment by diver2** [comment]
this was written in April, almost 3 months ago. Anyone knows if googleplus is now working with capacitor?

**Comment by jcesarmobile** [comment]
This needs to be fixed in the plugin, and the java code has not changed in the last 7 months, so no, it doesn't work yet.
It's an easy fix, just have to make the request code smaller, so you can try to send a PR and see if it gets merged.

**Comment by diver2** [comment]
@jcesarmobile Thanks... Posted issue there... :(

**Comment by arnaud-zad** [comment]
@diver2 I created a pull request. In waiting the merge, you can use my fork https://github.com/arnaud-zad/cordova-plugin-googleplus

**Comment by diver2** [comment]
@arnaud-zad  TKS!

**Comment by EddyVerbruggen** [comment]
Merged, will publish to npm any minute.

**Comment by jcesarmobile** [comment]
Thanks @EddyVerbruggen!
