### ISSUE TITLE
bug: (node:9794) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './capacitor.config.json'

### ISSUE THREAD

**Issue by gnu4cn** [ionic-team/capacitor#4065]
```console
(node:9794) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './capacitor.config.json'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:364:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.configCapacitor (/tmp/.mount_Yet-Anggn6lO/resources/app.asar/node_modules/@capacitor-community/electron/dist/esm-electron/Utils.js:74:39)
    at CapacitorElectronApp.init (/tmp/.mount_Yet-Anggn6lO/resources/app.asar/node_modules/@capacitor-community/electron/dist/esm-electron/CapacitorElectronApp.js:105:17)
    at App.Main.onReady (/tmp/.mount_Yet-Anggn6lO/resources/app.asar/build/index.js:85:29)
    at App.emit (events.js:322:22)
```

**Comment by jcesarmobile** [comment]
that looks like a capacitor-community/electron issue, please, report it on its repository

https://github.com/capacitor-community/electron/issues
