### ISSUE TITLE
bug: Android app crashes on run

### ISSUE THREAD

**Issue by nefarioustim** [ionic-team/capacitor#4372]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli: 3.0.0-rc.0
  @capacitor/core: 3.0.0-rc.0
  @capacitor/ios: 2.4.7
  @capacitor/android: 2.4.7

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

### Platform(s)

Android

### Current Behavior

I am attempting to build and test a PWA within Android. The build in Android Studio appears successful, installs the app on my testing device (physical), opens the app, but it immediately crashes with a FATAL, as shown in the LogCat output below.

### Expected Behavior

App should run successfully

### Code Reproduction

Our codebase is a Vue JS PWA. I will attempt to spin up a vanilla Vue build, wrap with Capacitor and update here with the result.

Update: Well that's frustrating. A vanilla build of a Vue.js PWA, and Capacitor is apparently fine. I shall continue to investigate to see if I can get some form of public replication of the issue.

### Other Technical Details

Using yarn, not npm.

`yarn --version` output: 1.22.10

`node --version` output: v15.11.0

### Additional Context

```
2021-03-19 15:53:42.756 6228-6228/? E/studio.deploy: Could not get package user id: run-as: unknown package: com.grafa
2021-03-19 15:53:42.788 6228-6228/? E/studio.deploy: Could not find apks for this package: com.grafa
2021-03-19 15:53:42.788 6228-6228/? E/studio.deploy: Error: 
2021-03-19 15:53:44.338 14200-14200/? E/Finsky: [2] VerifyPerSourceInstallationConsentInstallTask.f(2): Package name null is not an installed package
2021-03-19 15:53:44.409 623-2511/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::acquire()
2021-03-19 15:53:44.427 530-658/? E/Netd: getNetworkForDns: getNetId from enterpriseCtrl is netid 0
2021-03-19 15:53:44.680 530-658/? E/Netd: getNetworkForDns: getNetId from enterpriseCtrl is netid 0
2021-03-19 15:53:45.944 754-1089/? E/installd: Couldn't opendir /data/app/vmdl1743575976.tmp: No such file or directory
2021-03-19 15:53:45.944 754-1089/? E/installd: Failed to delete /data/app/vmdl1743575976.tmp: No such file or directory
2021-03-19 15:53:46.050 530-658/? E/Netd: getNetworkForDns: getNetId from enterpriseCtrl is netid 0
2021-03-19 15:53:46.162 623-2511/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::acquire()
2021-03-19 15:53:46.216 6308-6308/? E/rosoft.skydriv: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:46.335 4174-4174/? E/FILP/PackageIntentReceiver: This package is not a effect filter
2021-03-19 15:53:46.440 969-1243/? E/PkgPredictorService-Collector: record changed bt=1  wifi=1 screen=0
2021-03-19 15:53:46.477 6295-6295/? E/nder:appservic: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:46.638 4998-4998/com.grafa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.grafa, PID: 4998
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.Bridge.onStart()' on a null object reference
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:124)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8207)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3788)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2277)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-03-19 15:53:46.677 623-2511/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::acquire()
2021-03-19 15:53:46.681 4528-5198/? E/PBSessionCacheImpl: sessionId[19915970739951823] not persisted.
2021-03-19 15:53:46.702 1335-25518/? E/TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:587 android.os.Binder.execTransactInternal:1195 android.os.Binder.execTransact:1159 <bottom of call stack> 
2021-03-19 15:53:46.728 969-1000/? E/WindowManager: win=Window{450a00b u0 Splash Screen com.grafa EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5174 com.android.server.wm.ActivityRecord.destroySurfaces:5155 com.android.server.wm.WindowState.onExitAnimationDone:5570 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.ActivityRecord.onAnimationFinished:7089 com.android.server.wm.WindowContainer.doAnimationFinished:2639 
2021-03-19 15:53:46.966 566-600/? E/HYPER-HAL: [Request.cpp]acquire(): Request:: id : 491558, No Resource to set
2021-03-19 15:53:46.986 14200-14267/? E/Finsky: [1324] aqtg.b(3): Error while reading encrypted model
    java.security.GeneralSecurityException: decryption failed
        at bcyn.b(PG:7)
        at aqtg.b(PG:2)
        at aqpn.apply(Unknown Source:3)
        at j$.util.Optional.map(Optional.java:265)
        at aqrk.<init>(PG:6)
        at apqw.apply(Unknown Source:2)
        at j$.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at j$.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at j$.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at j$.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at j$.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at j$.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:132)
        at j$.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at j$.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at apqy.b(PG:13)
        at apwk.a(Unknown Source:13)
        at bctk.f(PG:2)
        at bctm.run(PG:9)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at pal.run(PG:4)
        at java.lang.Thread.run(Thread.java:923)
2021-03-19 15:53:46.991 2635-2635/? E/pageboostd: Received HALT command code 2
2021-03-19 15:53:47.032 6447-6447/? E/outineUIProces: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:47.215 6480-6480/? E/id.app.taskedg: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:47.337 6542-6542/? E/droid.easyMove: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:47.380 6573-6573/? E/.android.sclou: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:47.404 2635-6604/? E/pageboostd: prefetch start : app orgchromiumwebapka27fca704c097d000_v2
2021-03-19 15:53:47.408 6593-6593/? E/android.dqagen: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:47.423 2635-6604/? E/pageboostd: orgchromiumwebapka27fca704c097d000_v2, amt 36864 scnt 3 fcnt 2
2021-03-19 15:53:47.423 2635-6604/? E/pageboostd: prefetch end : app orgchromiumwebapka27fca704c097d000_v2 data_amount 36864
2021-03-19 15:53:47.426 623-2511/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::acquire()
2021-03-19 15:53:47.498 969-1010/? E/Watchdog: !@Sync: 93 heap: 79 / 99 [2021-03-19 15:53:47.498] sdogWay: softdog
2021-03-19 15:53:47.623 530-658/? E/Netd: getNetworkForDns: getNetId from enterpriseCtrl is netid 0
2021-03-19 15:53:47.713 6635-6635/? E/switchassistan: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:47.736 6649-6649/? E/d.game.gamehom: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:48.672 6804-6804/? E/droid.sm.polic: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:48.849 623-2511/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::acquire()
2021-03-19 15:53:49.297 6836-6836/? E/nder:appservic: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:49.452 969-1793/? E/ActivityTaskManager: MachinLearning intent received, starting MlLaunch
2021-03-19 15:53:49.498 5072-5072/? E/twitter.androi: Not starting debugger since process cannot load the jdwp agent.
2021-03-19 15:53:49.682 969-3314/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2021-03-19 15:53:49.861 969-1285/? E/system_server: Invalid class loader spec: =UnsupportedClassLoaderContext=
2021-03-19 15:53:49.861 969-1285/? E/PackageDexUsage: Unsupported context?
```

**Comment by nefarioustim** [comment]
Thanks @jcesarmobile. I basically just got there myself, having noticed my vanilla version had more stuff in the `capacitor.config.json`.

I have no idea how I managed to get 3.0.0-rc.0, since I just installed with `yarn add @capacitor/core @capacitor/cli`. Having dumped my branch and started over, it has installed 2.4.7 universally. I now have a working build on Android.

Thank you for responding. Closing this ticket.
