### ISSUE TITLE
bug: Share plugin crashes on Android if invoked twice in a row

### ISSUE THREAD

**Issue by daveshirman** [ionic-team/capacitor#4439]
### Capacitor Version
V3
```
npx cap --version
3.0.0-rc.0
```

### Platform(s)
Android

### Current Behavior

1. Invoke the share plugin from a click or something e.g.:
```
      <ion-item lines="none" detail="true" (click)="showShareApp()">
        <ion-icon name="share-outline" slot="start"></ion-icon>
        <ion-label>Share the app</ion-label>
      </ion-item> 
```

**html:**

```
  async showShareApp() {
    // BUG: Capacitor breaks if this is invoked twice in a row.
    await Share.share({
      title: "Title",
      url: "Someurl",
      text: "Some text",
      dialogTitle:"Some dialog title"
    });
  }
```

2. You'll see two share sheets appear.

3. Upon close of those sheets, app will crash with:
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1701612511, result=0, data=null} to activity {com.appname.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.getcapacitor.PluginCall.isKeptAlive()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5009)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Expected Behavior
No crash

### Code Reproduction
Literally open Share sheet exactly how your docs say, but twice in a row, see above.

### Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
You already reported this, but I moved the issue to capacitor-plugins repository
https://github.com/ionic-team/capacitor-plugins/issues/323
