### ISSUE TITLE
bug: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference

### ISSUE THREAD

**Issue by mirko77** [ionic-team/capacitor#4491]
## Bug Report

```
Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:542)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
        at com.getcapacitor.plugin.Filesystem.deleteFile(Filesystem.java:322)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:542) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 23 Capacitor plugins for ios:
    com-sarriaroman-photoviewer (1.2.5)
    cordova-plugin-androidx-adapter (1.1.3)
    cordova-plugin-camera (5.0.1)
    cordova-plugin-device (2.0.3)
    cordova-plugin-dialogs (2.0.2)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-transfer (2.0.0-dev)
    cordova-plugin-geolocation (4.0.2)
    cordova-plugin-globalization (1.11.0)
    cordova-plugin-googleplus (8.5.2)
    cordova-plugin-media (5.0.4-dev)
    cordova-plugin-media-capture (3.0.3)
    cordova-plugin-native-spinner (1.1.3)
    cordova-plugin-network-information (2.0.2)
    cordova-plugin-pdialog (2.0.1)
    cordova-plugin-sign-in-with-apple (0.1.2)
    cordova-plugin-splashscreen (5.0.3)
    cordova-sqlite-storage (2.2.0)
    cordova.plugins.diagnostic (6.0.3)
    phonegap-plugin-barcodescanner (8.1.0)
    cordova-plugin-ionic-webview (5.0.0)
    cordova-plugin-statusbar (2.4.3)
    cordova-plugin-whitelist (1.3.4)
[success] iOS looking great! 👌
```

### Platform(s)
Android 9

### Current Behavior
Application crashes when trying to delete a file at path `file:///data/user/0/{bundle_id}/files/photos/b963c3867b1441b89cb552b982f04bc8/84ca360f-c73e-4ed9-8678-88fc2d7cca8a_1619431013.jpg`

by calling the FileSystem plugin like so:

```
 Capacitor.Plugins.Filesystem.deleteFile({
  path: filepath,
  directory: ''
}).then(_onRemoveSuccess).catch(_onRemoveError);

```

### Expected Behavior
To delete the file without crashing. Works fine when deleting using the [Cordova filesystem plugin](https://github.com/apache/cordova-plugin-file)

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by mirko77** [comment]
Code reproduction here https://bitbucket.org/mirko77/file-delete/src/master/

Install the app
Take a photo
Click the delete button to try to delete the photo just taken
Open Logcat to find the crash log

**Comment by jcesarmobile** [comment]
If you want to use a file url, then don't pass an empty directory, just don't pass the directory option
FilesystemDirectory can only have this values
https://capacitorjs.com/docs/apis/filesystem#filesystemdirectory
