### ISSUE TITLE
bug: App crash when running in emulator

### ISSUE THREAD

**Issue by RoWEN-FCUB** [ionic-team/capacitor#4674]
Hello. When I run my Ionic proyect in a web emulator it works fine. But when I try to run it in Android Studio emulator crash. This is the error the console shows me:
```
Process: io.ionic.starter, PID: 16443
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.Bridge.onStart()' on a null object reference
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:124)
        at io.ionic.starter.MainActivity.onStart(MainActivity.java:8)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by jjgriff93** [comment]
I'm also facing this issue after clearing out my `/android` folder, updating capacitor and running `npx cap add android` and `npx cap open android`, then debugging the app in android studio.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.buildshare.buildshareapp, PID: 7215
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.Bridge.onStart()' on a null object reference
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:124)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8013)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3367)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7478)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

Cap Doctor:

Latest Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/core: 3.0.1
  @capacitor/android: 3.0.1
  @capacitor/ios: 3.0.1

Installed Dependencies:

  @capacitor/cli: 3.0.1
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7
  @capacitor/core: 2.4.2

[success] Android looking great! �
[error] Xcode is not installed

**Comment by jjgriff93** [comment]
@RoWEN-FCUB i've resolved my issue by updating `@capacitor/android` and `@capacitor/core` to `3.0.1` so all the versions are in sync, hopefully that will resolve your issue as well

**Comment by jcesarmobile** [comment]
closing since there was no response and could be related to not having capacitor versions in sync as jjgriff93 pointed out
