### ISSUE TITLE
Unable to load capacitor.config.json. Run npx cap copy first

### ISSUE THREAD

**Issue by dhwalin** [ionic-team/capacitor#4715]
My app is getting started but with following error in Android Studio. Please guide me if I am missing something.

I am following all steps. I have deleted android folder and add android again as well. But error is consistent.

Capacitor 3.0.1

```
D/Capacitor: Starting BridgeActivity
E/Capacitor: Unable to load capacitor.config.json. Run npx cap copy first
    java.io.FileNotFoundException: capacitor.config.json
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:957)
        at android.content.res.AssetManager.open(AssetManager.java:934)
        at com.getcapacitor.FileUtils.readFile(FileUtils.java:148)
        at com.getcapacitor.CapConfig.loadConfig(CapConfig.java:132)
        at com.getcapacitor.CapConfig.loadDefault(CapConfig.java:93)
        at com.getcapacitor.Bridge.<init>(Bridge.java:176)
        at com.getcapacitor.Bridge.<init>(Bridge.java:65)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1267)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:73)
        at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:54)
        at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:37)
        at com.dhwalin.bjpframes.MainActivity.onCreate(MainActivity.java:19)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by dhwalin** [comment]
Hello the problem was all the capacitor version was 3 and capacitor/cli was 2.

after making all capacitor version to 3, problem got solved.
