### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by bmitchinson** [ionic-team/capacitor#4857]
### Capacitor Version
(`npx cap` commands aren't working, but i have `@capacitor/ios @ 3.1.1` )

### Platform(s)
OS: M1 Mac: Big Sur 11.3
Node: 16.5.0
NPM: 7.20 (also tried on 6.14.13 but got the same error)

### Current Behavior
Using capacitor for the first time. [Guide](https://capacitorjs.com/docs/ios) suggests adding it to an existing project, so I decided to add it to a create-react-app project.

`npx create-react-app haptic-test --template typescript`
`cd hapitc-test`
`npm i @capacitor/ios`
`npx cap add ios`: yields -> `npm ERR! could not determine executable to run`

```
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bmitchinson/.npm/_logs/2021-07-21T01_38_18_381Z-debug.log

cat /Users/bmitchinson/.npm/_logs/2021-07-21T01_38_18_381Z-debug.log

0 verbose cli [
0 verbose cli   '/Users/bmitchinson/.nvm/versions/node/v16.5.0/bin/node',
0 verbose cli   '/Users/bmitchinson/.nvm/versions/node/v16.5.0/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'cap',
0 verbose cli   'add',
0 verbose cli   'ios'
0 verbose cli ]
1 info using npm@7.20.0
2 info using node@v16.5.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/bmitchinson/.nvm/versions/node/v16.5.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/bmitchinson/repos/personal/haptic-test/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/Users/bmitchinson/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/bmitchinson/.nvm/versions/node/v16.5.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 3ms
19 timing npm:load:configload Completed in 3ms
20 timing npm:load:setTitle Completed in 9ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 0ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 14ms
26 timing config:load:flatten Completed in 1ms
27 http fetch GET 200 https://registry.npmjs.org/cap 155ms (cache revalidated)
28 timing command:exec Completed in 169ms
29 verbose stack Error: could not determine executable to run
29 verbose stack     at getBinFromManifest (/Users/bmitchinson/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:15:23)
29 verbose stack     at exec (/Users/bmitchinson/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:113:15)
30 verbose pkgid cap@0.2.1
31 verbose cwd /Users/bmitchinson/repos/personal/haptic-test
32 verbose Darwin 20.4.0
33 verbose argv "/Users/bmitchinson/.nvm/versions/node/v16.5.0/bin/node" "/Users/bmitchinson/.nvm/versions/node/v16.5.0/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "cap" "add" "ios"
34 verbose node v16.5.0
35 verbose npm  v7.20.0
36 error could not determine executable to run
37 verbose exit 1
```

### Expected Behavior
`npx cap` or `npx capacitor` should resolve to the local node_modules to execute. Neither work.

### Code Reproduction
[This repo](https://github.com/bmitchinson/cra_typescript) is what i'm trying to run `npx cap ...` from. It's literally just the output of `npx create-react-app haptic-test --template typescript` and then `npm i @capacitor/ios`, so it's nothing exciting.

### Additional Context
Saw [this related issue](https://github.com/ionic-team/capacitor/issues/4351) which recommended trying npm6 instead of 7. Tried that, got the same results.

**Comment by IT-MikeS** [comment]
Ref: (Capacitor Docs)[https://capacitorjs.com/docs/getting-started#adding-capacitor-to-your-app]

The steps you took to get Capacitor setup are a bit out of whack here, please try these ones below and let me know if you have further issues!

1. `npx create-react-app haptic-test --template typescript`
2. `cd hapitc-test`
3. `npm install @capacitor/core @capacitor/cli`
4. `npx cap init` - The CLI will ask you a few questions, starting with your app name, and the package id you would like to use for your app.Last, it will ask what directory your web assets get built into. For Angular, this is www, React is build, and Vue is dist. If you don’t know right now, you can update this value in the capacitor.config.ts file later.
5. `npm run build`
6. `npm install @capacitor/ios`
7. `npx cap add ios`
8. (Follow this doc entry to run and use the iOS platform)[https://capacitorjs.com/docs/ios#opening-the-ios-project]

Hope this helps 👍

**Comment by bmitchinson** [comment]
This worked perfectly. Thank you for your help.

Got an issue where cocopods was freaking out on m1 during `npx cap add ios`, so i did `sudo gem uninstall cocopods` and installed it this way with the `ffi` package. Then things worked great + I built the app in xCode https://stackoverflow.com/a/64901980

I went through the getting started section of the docs to be sure that I followed the setup steps, but I guess I thought adding capacitor and adding a capacitor "platform" were the same thing. Don't know how I wasn't able to notice the differences but anyway, thank you.

**Comment by IT-MikeS** [comment]
No worries, glad to help!
