### ISSUE TITLE
bug: App crashed immediately after start

### ISSUE THREAD

**Issue by timrosskamp** [ionic-team/capacitor#5444]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

I'm trying to start the App in Android Studio on a Pixel 4 API 30. Almost immediately the app crashed with this error:

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setFitsSystemWindows(boolean)' on a null object reference
        at com.capacitorjs.plugins.splashscreen.SplashScreen.buildViews(SplashScreen.java:224)
        at com.capacitorjs.plugins.splashscreen.SplashScreen.show(SplashScreen.java:291)
        at com.capacitorjs.plugins.splashscreen.SplashScreen.showOnLaunch(SplashScreen.java:58)
        at com.capacitorjs.plugins.splashscreen.SplashScreenPlugin.load(SplashScreenPlugin.java:21)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:95)
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:59)
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:503)
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:458)
        at com.getcapacitor.Bridge.<init>(Bridge.java:188)
        at com.getcapacitor.Bridge.<init>(Bridge.java:65)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1288)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8018)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by timrosskamp** [comment]
I managed to fix it. I forgot to add the name of the splash resource to the capacitor config file:

```
{
  "plugins": {
    "SplashScreen": {
      "androidSplashResourceName": "ic_splash_vektor"
    }
  }
}
```

**Comment by adelabd** [comment]
I have exactly the same problem only for some devices 
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/28626565/160198446-a0421588-3376-4b95-834b-044570ee3ef5.png">

**Comment by adelabd** [comment]
The problem was that my splash.png was missing for land-xxhdpi and port-hdpi. It was not caused directly by the plugin.

By the way, the androidSplashResourceName seems to be mandatory only if the name is differen than "splash".

Good luck !
