### ISSUE TITLE
bug: Samsung - Lock screen appearing on app open

### ISSUE THREAD

**Issue by HipyCas** [ionic-team/capacitor#5452]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/android: 3.3.3
  @capacitor/core: 3.3.2
  @capacitor/ios: 3.3.3

[success] Android looking great! 👌
```

### Platform(s)

Android, precisely some Samsung devices (tested on Samsung Galaxy S10+, Samsung A52 and SamsungA53; also tested on Samsung A51S but seemed to work there)

### Current Behavior

When the app is opened, the lock screen appears after most of the screen turns black, getting the phone locked and requiring to unlock it again. It happens multiple time before the app comes into view, repeating the process in the moment you unlock the phone fairly quickly. I cannot find the issue that may be causing this, and what I have found in the logs I have no idea what it means or how I can solve it.

### Expected Behavior

As simple as opening the app, the lock screen should not appear but rather the splash screen and the app contents later. My only guess is that maybe the splash screen is not working properly.

### Code Reproduction

The code of the application where the bug appears con be found in [@biocienciasgrx/ceebi](https://github.com/biocienciasgrx/ceebi). As I have not the slightest idea where the error may be, I cannot be more precise than this.

### Other Technical Details

`npm --version` output: 7.20.2

`node --version` output: v16.4.1

### Additional Context

You can find the debug logs from Android Studio of a Samsung Galaxy S10+ that shows this issue in the following gist (too long to paste it here): https://gist.github.com/HipyCas/8e86980ca673b0c86440938d7de883c0

**Comment by shaibrown5** [comment]
I can confirm this. 

The exact same behavior has been happening with my app on mainly Samsung phones. It locks automatically about 3 times and afterward, I am able to use the app properly. In all cases, I ran the app directly on the physical device.
 I have tried it on :
  - **s20 FE** - android 12
  - **s21** - andoid 12
  - **s21 +** - android 12

I have also tried in on the new **A52** and it worked - But this was the only device running on **android 11** and not **android 12**.
Furthermore, I am experiencing the same behavior on **Pixel 4a** running on android 12 as well


the main error that I believe is causing this is:
```
E/Capacitor/Console: File: https://mobile.orgname.io/ - Line 1 - Msg: Uncaught TypeError: Cannot read properties of undefined (reading 'triggerEvent')
```
But I am not sure what this means. 
I have gone over a similar issue #2183 but wasn't able to solve the problem

other details:
![image](https://user-images.githubusercontent.com/49106059/155532773-935dca86-c5b0-4e1e-a612-992c8362f9c0.png)

**Comment by jcesarmobile** [comment]
I can reproduce with the provided app (on the pixel 5 with Android 12 from browserstack) , but not on the test app we use for testing all plugins (https://github.com/ionic-team/capacitor-testapp)
I removed the @robingenz/capacitor-app-update plugin and the update code and I couldn't reproduce anymore.
Before that, I added this variable to variables.gradle file `androidPlayCore = '1.10.3'` so the plugin used the latest play core version in case it had some issues with Android 12, but didn't change anything

shaibrown5, are you also using that plugin? I don't see it in the screenshot.
The error you mention can happen if the plugins code has not been injected properly, but I don't think it would cause any problems (other than the plugins won't work)

**Comment by jcesarmobile** [comment]
would be helpful if you could also provide a sample app

**Comment by shaibrown5** [comment]
@jcesarmobile While creating the sample app I solved the issue I managed to replicate the bug and solve the issue

My styles.xml file under src/main/res/values/styles.xml looks l like this:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

    <style name="AppTheme.NoActionBar" parent="Theme.AppCompat.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:background">@null</item>
    </style>


    <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
        <item name="android:background">@layout/launch_screen</item>
    </style>
</resources>
```

this line was the problem:
```        <item name="android:background">@layout/launch_screen</item>```
launch_screen is XML and as soon as I changed it to either @null or to the default @drawable/splash the problem solved itself. 

@HipyCas try changing yours as well, see if it works for you. It's weird that this works on other android versions and only now it crashes.

**Comment by HipyCas** [comment]
I have been able to resolve the issue using @shaibrown5's solution, at least in one of the my test devices (Samsung Galaxy S10+). As a temporary solution, I can perfectly use it, but in the long term, I hope the issue gets fixed, though I don't know if it's a problem with Capacitor or Android itself. I have not tried to remove the plugin as @jcesarmobile suggesting, but due to the fact that this error showed up in projects not using that plugin, didn't find it interesting to do that test. Thanks all for your help! And hope this gets fixed soon! (Maybe it's better to open a new issue or rename it)

**Comment by yoyo930021** [comment]
In my case, I will fix it in xml.
You can try to find debug logs and not filter only app id logs.

You can find out about some like error.
```
2022-03-22 15:31:58.055 32354-32414/? E/AndroidRuntime: FATAL EXCEPTION: wmshell.splashscreen
    Process: com.android.systemui, PID: 32354
    android.content.res.Resources$NotFoundException: Drawable win.ga.app.main0dev:drawable/splash_theme with resource ID #0x7f0700ad
    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/splash_theme.xml from drawable resource ID #0x7f0700ad
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:1039)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:721)
        at android.content.res.Resources.loadDrawable(Resources.java:1069)
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1007)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:982)
        at android.view.View.<init>(View.java:5810)
        at android.view.ViewGroup.<init>(ViewGroup.java:720)
        at android.view.ViewGroup.<init>(ViewGroup.java:716)
        at android.view.ViewGroup.<init>(ViewGroup.java:712)
        at android.view.ViewGroup.<init>(ViewGroup.java:708)
        at android.widget.FrameLayout.<init>(FrameLayout.java:85)
        at com.android.wm.shell.startingsurface.StartingSurfaceDrawer.addSplashScreenStartingWindow(StartingSurfaceDrawer.java:306)
        at com.android.wm.shell.startingsurface.StartingWindowController.lambda$addStartingWindow$0(StartingWindowController.java:143)
        at com.android.wm.shell.startingsurface.StartingWindowController.$r8$lambda$PSvN_iYbAze6X2c1OXkMhBsWeHo(Unknown Source:0)
        at com.android.wm.shell.startingsurface.StartingWindowController$$ExternalSyntheticLambda4.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #5: <item> tag requires a 'drawable' attribute or child tag defining a drawable
        at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:279)
        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:200)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:149)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1426)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1385)
        at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:1071)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:1010)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:721) 
        at android.content.res.Resources.loadDrawable(Resources.java:1069) 
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1007) 
        at android.content.res.TypedArray.getDrawable(TypedArray.java:982) 
        at android.view.View.<init>(View.java:5810) 
        at android.view.ViewGroup.<init>(ViewGroup.java:720) 
        at android.view.ViewGroup.<init>(ViewGroup.java:716) 
        at android.view.ViewGroup.<init>(ViewGroup.java:712) 
        at android.view.ViewGroup.<init>(ViewGroup.java:708) 
        at android.widget.FrameLayout.<init>(FrameLayout.java:85) 
        at com.android.wm.shell.startingsurface.StartingSurfaceDrawer.addSplashScreenStartingWindow(StartingSurfaceDrawer.java:306) 
        at com.android.wm.shell.startingsurface.StartingWindowController.lambda$addStartingWindow$0(StartingWindowController.java:143) 
        at com.android.wm.shell.startingsurface.StartingWindowController.$r8$lambda$PSvN_iYbAze6X2c1OXkMhBsWeHo(Unknown Source:0) 
        at com.android.wm.shell.startingsurface.StartingWindowController$$ExternalSyntheticLambda4.run(Unknown Source:6) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by Lucas-Wanat** [comment]
I'm having a similar problem, in my case I have an app that uses serial bluetooth, this part of bluetooth has nothing to do with it, but my app has a login screen in it I use an api that in that we have a post request using httpclient from angular itself, and if the login is right it redirects using the NavController from @ionic/angular. I've already tested it on my GalaxyJ4 core with android 8.1 and on a Semp also android 8.1, and both worked correctly, but when I tested it on a Galaxy Tab A8 android 11, and it just doesn't access the app screen even with the correct login I'm analyzing it 2 days ago and it seems that it doesn't even execute the request, anyway, it's just not going, maybe because of this bug or another similar bug. I hope we find an answer, and I'd be very grateful if you get the solution.

**Comment by jcesarmobile** [comment]
This seems to be a problem with the configured xml file to be used as `android:background` value.
When you hover over it on Android Studio it shows red lines instead of the preview, which makes me think it doesn't have the correct format.
Same happens to the other drawables the xml file uses internally.
Switching to using the png instead of the xml fixes the issue.

I've tested the same xml on a native Android app and the problem still reproduces, so it's not related to Capacitor. It's probably some Android bug that only affects certain devices.
