### ISSUE TITLE
bug: Error: "Geolocation" plugin is not implemented on android

### ISSUE THREAD

**Issue by tigohenryschultz** [ionic-team/capacitor#5497]
### Capacitor Version

```
PS C:\repos\tigosmart> npx cap doctor
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3
  @capacitor/android: 3.4.3

[success] Android looking great! �
[error] Xcode is not installed
```

### Platform(s)
Android

### Current Behavior
Geolocation keeps throwing this error, other plugins updated just fine from Capacitor 2 -> 3.

### Expected Behavior
Doesn't throw an error

### Other Technical Details

`npm --version` output: 6.14.13

`node --version` output: v14.17.3

`pod --version` output (iOS issues only):

### Additional Context
![image](https://user-images.githubusercontent.com/75696293/157744331-e4f60fd8-b456-464b-bb60-cf0ae0086e24.png)

`
geolocation.js:105 Error: "Geolocation" plugin is not implemented on android
    at createPluginMethod (index.js:187:1)
    at index.js:194:1
(anonymous)	@	geolocation.js:105
Promise.catch (async)		
(anonymous)	@	geolocation.js:95
getCurrentPosition	@	geolocation.js:94
wrappedActionHandler	@	vuex.esm-browser.js:305
dispatch	@	vuex.esm-browser.js:1031
boundDispatch	@	vuex.esm-browser.js:914
setup	@	TgGoogleMap.vue:79
callWithErrorHandling	@	runtime-core.esm-bundler.js:155
setupStatefulComponent	@	runtime-core.esm-bundler.js:7044
setupComponent	@	runtime-core.esm-bundler.js:7000
mountComponent	@	runtime-core.esm-bundler.js:4921
processComponent	@	runtime-core.esm-bundler.js:4896
patch	@	runtime-core.esm-bundler.js:4488
componentUpdateFn	@	runtime-core.esm-bundler.js:5106
run	@	reactivity.esm-bundler.js:167
updateComponent	@	runtime-core.esm-bundler.js:4967
processComponent	@	runtime-core.esm-bundler.js:4900
patch	@	runtime-core.esm-bundler.js:4488
patchKeyedChildren	@	runtime-core.esm-bundler.js:5261
patchChildren	@	runtime-core.esm-bundler.js:5204
patchElement	@	runtime-core.esm-bundler.js:4720
processElement	@	runtime-core.esm-bundler.js:4568
patch	@	runtime-core.esm-bundler.js:4485
componentUpdateFn	@	runtime-core.esm-bundler.js:5106
run	@	reactivity.esm-bundler.js:167
updateComponent	@	runtime-core.esm-bundler.js:4967
processComponent	@	runtime-core.esm-bundler.js:4900
patch	@	runtime-core.esm-bundler.js:4488
patchKeyedChildren	@	runtime-core.esm-bundler.js:5261
patchChildren	@	runtime-core.esm-bundler.js:5204
Promise.then (async)		
queueFlush	@	runtime-core.esm-bundler.js:285
queueJob	@	runtime-core.esm-bundler.js:279
(anonymous)	@	runtime-core.esm-bundler.js:5138
triggerEffects	@	reactivity.esm-bundler.js:359
triggerRefValue	@	reactivity.esm-bundler.js:957
set value	@	reactivity.esm-bundler.js:1001
set	@	reactivity.esm-bundler.js:1016
set	@	runtime-core.esm-bundler.js:6762
ionViewDidEnter	@	TgSystemAddress.vue:78
fireLifecycle	@	index.esm.js:908
handlePageTransition	@	index.esm.js:1332
await in handlePageTransition (async)		
handlePageTransition	@	index.esm.js:1301
enteringViewItem.registerCallback	@	index.esm.js:1363
registerIonPage	@	index.esm.js:1391
registerIonPage	@	index.esm.js:1424
mounted	@	index.esm.js:1052
callWithErrorHandling	@	runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling	@	runtime-core.esm-bundler.js:164
hook.__weh.hook.__weh	@	runtime-core.esm-bundler.js:2667
flushPostFlushCbs	@	runtime-core.esm-bundler.js:356
flushJobs	@	runtime-core.esm-bundler.js:401
Promise.then (async)		
queueFlush	@	runtime-core.esm-bundler.js:285
queueJob	@	runtime-core.esm-bundler.js:279
(anonymous)	@	runtime-core.esm-bundler.js:5138
triggerEffects	@	reactivity.esm-bundler.js:359
triggerRefValue	@	reactivity.esm-bundler.js:957
(anonymous)	@	reactivity.esm-bundler.js:1088
triggerEffects	@	reactivity.esm-bundler.js:359
triggerRefValue	@	reactivity.esm-bundler.js:957
set value	@	reactivity.esm-bundler.js:1001
finalizeNavigation	@	vue-router.esm-bundler.js:3194
(anonymous)	@	vue-router.esm-bundler.js:3067
Promise.then (async)		
pushWithRedirect	@	vue-router.esm-bundler.js:3038
push	@	vue-router.esm-bundler.js:2966
nextPage	@	TgSystemInfo.vue:152
callWithErrorHandling	@	runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling	@	runtime-core.esm-bundler.js:164
emit$1	@	runtime-core.esm-bundler.js:718
Object.onClick._cache.<computed>._cache.<computed>	@	TgButton.vue:7
(anonymous)	@	runtime-dom.esm-bundler.js:380
callWithErrorHandling	@	runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling	@	runtime-core.esm-bundler.js:164
callWithAsyncErrorHandling	@	runtime-core.esm-bundler.js:174
invoker	@	runtime-dom.esm-bundler.js:366
`

**Comment by tigohenryschultz** [comment]
Deleeting the main activity oncreate solved it.

![image](https://user-images.githubusercontent.com/75696293/157747046-21f98cb9-1031-461f-91b0-e5d3f456b214.png)

**Comment by tigohenryschultz** [comment]
The capacitor CLI console commands should probably solve this automatically..
