### ISSUE TITLE
Problem in build android

### ISSUE THREAD

**Issue by shomid** [ionic-team/capacitor#584]
I have a ionic 3 project.
I added capacitor to my project.
get error in the following when build project in android studio 3.1.3 :

    `org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':capacitor-android-plugins'.
    at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:109)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:68)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:37)
    at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:125)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
     at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
     at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
      at  org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:52)
     at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:677)
     at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:138)
     at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
     at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
     at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:100)
    at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:81)
    ... more

    Caused by: java.lang.NumberFormatException: For input string: "+"
     at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:572)
    at java.lang.Integer.valueOf(Integer.java:766)
    at java_lang_Integer$valueOf.call(Unknown Source)
    at com.google.gms.googleservices.GoogleServicesPlugin.checkMinimumVersion(GoogleServicesPlugin.groovy:88)
    at com.google.gms.googleservices.GoogleServicesPlugin.addDependency(GoogleServicesPlugin.groovy:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    ... more`

dependencies:

    `"@ionic-native/contacts": "4.7.0",
        "@ionic-native/core": "4.7.0",
        "@ionic-native/device": "4.7.0",
        "@ionic-native/diagnostic": "^4.7.0",
        "@ionic-native/fcm": "^4.7.0",
        "@ionic-native/file": "^4.7.0",
        "@ionic-native/file-opener": "^4.7.0",
        "@ionic-native/file-transfer": "^4.7.0",
        "@ionic-native/geolocation": "^4.7.0",
        "@ionic-native/in-app-browser": "4.7.0",
        "@ionic-native/network": "4.7.0",
        "@ionic-native/sim": "4.7.0",
        "@ionic-native/social-sharing": "4.7.0",
        "@ionic-native/splash-screen": "4.7.0",
        "@ionic-native/status-bar": "^4.7.0",
        "@ionic/storage": "2.1.3",
        "@ngx-translate/core": "9.1.1",
        "@ngx-translate/http-loader": "2.0.1",
        "@types/leaflet": "1.2.7",
        "com.lampa.startapp": "^0.1.4",
        "cordova-android": "^7.0.0",
        "cordova-plugin-compat": "1.2.0",
        "cordova-plugin-console": "^1.1.0",
        "cordova-plugin-contacts": "^3.0.1",
        "cordova-plugin-device": "^2.0.2",
        "cordova-plugin-fcm": "^2.1.2",
        "cordova-plugin-file": "^6.0.1",
        "cordova-plugin-file-opener2": "^2.0.19",
        "cordova-plugin-file-transfer": "^1.7.1",
        "cordova-plugin-geolocation": "^4.0.1",
        "cordova-plugin-inappbrowser": "^3.0.0",
        "cordova-plugin-network-information": "^2.0.1",
        "cordova-plugin-sim": "^1.3.3",
        "cordova-plugin-splashscreen": "^5.0.2",
        "cordova-plugin-statusbar": "^2.4.2",
        "cordova-plugin-whitelist": "^1.3.3",
        "cordova-plugin-x-socialsharing": "^5.4.0",
        "cordova.plugins.diagnostic": "^4.0.8",`

**Comment by raxim1** [comment]
I have used empty angular cli project, and no problem at all. I would suggest to remove cordova-android from your project, and step by step all the plugins. Nobody told you that it will work smoothly with all the buggy cordova plugins.

**Comment by jcesarmobile** [comment]
Can you try to remove "cordova-plugin-fcm"? I think the problem comes from there.

If that fixes the problem, you'll have to do some manual edits to the plugins gradle file and to your projects gradle files too, as last release of that plugin is from one year ago and it's not merging any of the PRs that people is sending.

**Comment by jcesarmobile** [comment]
The problem seems related to cordova-plugin-fcm as it sets the versions with +. 
This could probably be overriden by specifying a fixed versions in the app's build.gradle.

Please, try that, and if it doesn't fix your issue, reopen and provide more information

**Comment by erickmagalhaes** [comment]
Hi  capacitor need reinstall  all pguins  and some case you need a new implementation  to fcm use this
  https://www.npmjs.com/package/capacitor-fcm
