### ISSUE TITLE
bug: deploying app to physical iOS device fails

### ISSUE THREAD

**Issue by ramikhafagi96** [ionic-team/capacitor#5881]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/ios: 4.0.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Platform: iOS

### Current Behavior

When I run `ionic cap ios run -l --external` and choose my physical iOS device (iPhone 13 Pro with iOS 15.6) I get this error. However, choosing the emulator it works just fine!
```
capacitor run ios --no-sync --target <device-udid>
[capacitor] ✔ Running xcodebuild in 21.98s
[capacitor] ✖ Deploying cartona.app to <device-udid> - failed!
[capacitor] [error] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 57. Received 58
[capacitor]         at new NodeError (node:internal/errors:372:5)
[capacitor]         at boundsError (node:internal/buffer:86:9)
[capacitor]         at writeU_Int8 (node:internal/buffer:741:5)
[capacitor]         at Buffer.writeUInt8 (node:internal/buffer:748:10)
[capacitor]         at toCString (/Users/rami-cartona/workspace/retailer-app/node_modules/native-run/dist/ios/lib/client/afc.js:162:9)
[capacitor]         at AFCClient.makeDirectory (/Users/rami-cartona/workspace/retailer-app/node_modules/native-run/dist/ios/lib/client/afc.js:89:19)
[capacitor]         at uploadDir (/Users/rami-cartona/workspace/retailer-app/node_modules/native-run/dist/ios/lib/client/afc.js:107:41)
[capacitor]         at /Users/rami-cartona/workspace/retailer-app/node_modules/native-run/dist/ios/lib/client/afc.js:107:78
[capacitor]         at processTicksAndRejections (node:internal/process/task_queues:96:5)
[capacitor]         at async Promise.all (index 7)
[capacitor]         node:events:505
[capacitor]         throw er; // Unhandled 'error' event
[capacitor]         ^
[capacitor]
[capacitor]         Error [ERR_STREAM_WRITE_AFTER_END]: write after end
[capacitor]         at new NodeError (node:internal/errors:372:5)
[capacitor]         at _write (node:internal/streams/writable:319:11)
[capacitor]         at Socket.Writable.write (node:internal/streams/writable:334:10)
[capacitor]         at AFCProtocolWriter.write (/Users/rami-cartona/workspace/retailer-app/node_modules/native-run/dist/ios/lib/protocol/afc.js:361:16)
[capacitor]         at /Users/rami-cartona/workspace/retailer-app/node_modules/native-run/dist/ios/lib/protocol/afc.js:300:25
[capacitor]         at new Promise (<anonymous>)
[capacitor]         at AFCProtocolClient.sendMessage (/Users/rami-cartona/workspace/retailer-app/node_modules/native-run/dist/ios/lib/protocol/afc.js:286:16)
[capacitor]         at AFCClient.openFile (/Users/rami-cartona/workspace/retailer-app/node_modules/native-run/dist/ios/lib/client/afc.js:53:48)
[capacitor]         at AFCClient.uploadFile (/Users/rami-cartona/workspace/retailer-app/node_modules/native-run/dist/ios/lib/client/afc.js:74:24)
[capacitor]         Emitted 'error' event on Socket instance at:
[capacitor]         at emitErrorNT (node:internal/streams/destroy:157:8)
[capacitor]         at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[capacitor]         at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[capacitor]         code: 'ERR_STREAM_WRITE_AFTER_END'
[capacitor]         }
[capacitor]
[ERROR] An error occurred while running subprocess capacitor.

        capacitor run ios --no-sync --target <device-udid> exited
        with exit code 1.

        Re-running this command with the --verbose flag may provide more
        information.
```

### Expected Behavior

It should deploy the app to the device successfully.

### Other Technical Details

`yarn --version` output: v3.2.2

`node --version` output: v16.15.1

`pod --version` output (iOS issues only): 1.11.3

**Comment by ramikhafagi96** [comment]
the error is gone after upgrading node to `v18.7.0`, but the logs shows the app is deployed to the device successfully but it actually it's not
```
[capacitor] ✔ Running xcodebuild in 15.08s
[capacitor] ✔ Deploying cartona.app to <device-udid> in 427.54ms

[INFO] App deployed to device!
```

**Comment by jcesarmobile** [comment]
Have you configured the signing for your app? (i.e. selecting the development team from Xcode).
If you haven't, that would explain why it works on simulators but not on real device, run command doesn't handle signing, so if your project can't be run from Xcode it can't be run with run command neither.

It should show an error like
> Signing for "App" requires a development team. Select a development team in the Signing & Capabilities editor.

But looks like there is a problem with the returned error being out of range.

**Comment by ramikhafagi96** [comment]
@jcesarmobile the signing is handled, actually in the logs it says that the app is deployed to the device but actually it's not deployed

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
