### ISSUE TITLE
bug: Cookie does not become available to other clients / transports

### ISSUE THREAD

**Issue by WillooWisp** [ionic-team/capacitor#5943]
### Capacitor Version
```
Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0
  @capacitor/android: 4.3.0

[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)
Android (not tested on iOS yet)

### Current Behavior
Using a library like SignalR from Microsoft that out of the box supports cookie authentication when performing web socket calls does not seem to work on devices, but it works in browser on PC. Before Capacitor 4.3 we got CORS problems, but now we get passed this and the problem is the authentication errors when performing the web socket calls.

```
Error: Failed to invoke 'subscribe' because user is unauthorized
    at _callbacks.<computed> (HubConnection.js:308:36)
    at HubConnection._processIncomingData (HubConnection.js:420:33)
```

### Expected Behavior
Expects authenticated web socket calls to just work, since cookie should be passed on.

### Code Reproduction
```
this.hubConnection = new HubConnectionBuilder()
  .withAutomaticReconnect(new InfiniteRetryPolicy())
  .configureLogging(LogLevel.Information)
  .withUrl(`${this.host.endsWith('/') ? this.host : `${this.host}/`}signalrhub`)
.build();

this.subscribedNodes = [];
await this.subscribeToNodes(nodes);
});

await this.hubConnection.start();
await this.hubConnection.invoke('subscribe'); // Fails on devices when authentication is required on the SignalR Hub in backend
```

### Other Technical Details
"@microsoft/signalr": "~6.0.9"

`npm --version` output: 8.11.0
`yarn version` output: v1.22.19
`node --version` output: v16.16.0

### Additional Context
```
plugins: {
		pushNotifications: {
			presentationOptions: ['badge', 'sound', 'alert'],
		},
		SplashScreen: {
			launchAutoHide: false,
			backgroundColor: '#00000000',
			androidSplashResourceName: 'splash',
			androidScaleType: 'FIT_CENTER',
			showSpinner: true,
			androidSpinnerStyle: 'large',
			iosSpinnerStyle: 'small',
			spinnerColor: '#999999',
			splashFullScreen: false,
			splashImmersive: false,
			layoutName: 'launch_screen',
			useDialog: false
		  },
		  CapacitorCookies: {
			enabled: true
		  },
		  CapacitorHttp: {
			enabled: true
		  }
	}
```

**Comment by nicklasuhde** [comment]
I have the same issue!

**Comment by ItsChaceD** [comment]
Can you please test with this dev release and see if the problem still occurs:
`4.5.1-dev-20221117T024619.0`

```
npm i @capacitor/android@4.5.1-dev-20221117T024619.0
npm i @capacitor/core@4.5.1-dev-20221117T024619.0
npm i @capacitor/ios@4.5.1-dev-20221117T024619.0
```

**Comment by WillooWisp** [comment]
I will test this today.

**Comment by ItsChaceD** [comment]
Thanks for all of the information @WillooWisp !
Are you able to provide a project or repo for me to test against? I have a general idea of what may be causing this, but I'd like to do some further discovery & I don't have a server set up for this specific use case.

**Comment by eric-horodyski** [comment]
This thread has been inactive for some time, and we’re cleaning up older items to keep the backlog focused and manageable.

Details on the effort:
[https://ionic.io/blog/keeping-capacitors-backlog-healthy](https://ionic.io/blog/keeping-capacitors-backlog-healthy)

If this is still relevant today, feel free to open a new issue with current information and we’ll review it.
