### ISSUE TITLE
bug: Unable to get provider androidx.core.content.FileProvider: java.lang.SecurityException: Provider must not be exported

### ISSUE THREAD

**Issue by ImAbhishekTomar** [ionic-team/capacitor#5987]
I am facing this issue after updating my capacitor v3 to v4, my app is crashing on the initial load and showing the below issue.

## Bug Report
```
FATAL EXCEPTION: main
Process: com.rskbsl.ssralx, PID: 5233
java.lang.RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.SecurityException: Provider must not be exported
 at android.app.ActivityThread.installProvider(ActivityThread.java:7436)
 at android.app.ActivityThread.installContentProviders(ActivityThread.java:6948)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
 at android.app.ActivityThread.access$1500(ActivityThread.java:256)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7842)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.SecurityException: Provider must not be exported
 at androidx.core.content.FileProvider.attachInfo(FileProvider.java:413)
 at android.app.ActivityThread.installProvider(ActivityThread.java:7431)
 at android.app.ActivityThread.installContentProviders(ActivityThread.java:6948) 
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719) 
 at android.app.ActivityThread.access$1500(ActivityThread.java:256) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090) 
 at android.os.Handler.dispatchMessage(Handler.java:106) 
 at android.os.Looper.loopOnce(Looper.java:201) 
 at android.os.Looper.loop(Looper.java:288) 
 at android.app.ActivityThread.main(ActivityThread.java:7842) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```
### Capacitor Version

```
1 
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[error] Missing <manifest package=""> attribute in app/src/main
```

### Other Technical Details

`npm --version` output:
8.19.2
`node --version` output:
v16.15.0
`pod --version` output (iOS issues only):
1.11.3
### Additional Context

```

(base) *[FIX-GRADLE-E1][~/desktop/root/rsk/source/ssralx]$ ionic info                                                              rbenv:3.0.1 

Ionic:

   Ionic CLI                     : 6.20.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.0
   @angular-devkit/build-angular : 13.3.9
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : 4.3.0
   @capacitor/core    : 4.3.0
   @capacitor/ios     : 4.3.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.15.0 (/usr/local/bin/node)
   npm    : 8.19.2
   OS     : macOS Monterey

```
**AndroidManifest.xml**
```

<?xml version='1.0' encoding='utf-8'?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
    <application android:allowBackup="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:requestLegacyExternalStorage="true" android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:theme="@style/AppTheme" android:usesCleartextTraffic="true" tools:targetApi="m">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:exported="true" android:label="@string/title_activity_main" android:launchMode="singleTask" android:name="com.rskbsl.ssralx.MainActivity" android:theme="@style/AppTheme.NoActionBarLaunch">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <provider android:authorities="${applicationId}.fileprovider" android:exported="true" android:grantUriPermissions="true" android:name="androidx.core.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
        </provider>
    </application>
    <uses-permission android:name="android.permission.INTERNET" tools:ignore="ManifestOrder" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:ignore="ScopedStorage" />
</manifest>

```

**variables.gradle**
```

ext {
  minSdkVersion = 22
  compileSdkVersion = 32
  targetSdkVersion = 32
  androidxActivityVersion = '1.4.0'
  androidxAppCompatVersion = '1.5.1'
  androidxCoordinatorLayoutVersion = '1.2.0'
  androidxCoreVersion = '1.8.0'
  androidxFragmentVersion = '1.4.1'
  coreSplashScreenVersion = '1.0.0-rc01'
  androidxWebkitVersion = '1.4.0'
  junitVersion = '4.13.2'
  androidxJunitVersion = '1.1.3'
  androidxEspressoCoreVersion = '3.4.0'
  cordovaAndroidVersion = '10.1.1'
  appNamespace='com.rskbsl.ssralx'
}

```

**Comment by jcesarmobile** [comment]
how did you migrate? 
manually? `npx cap migrate` command? vs code extension?

**Comment by ImAbhishekTomar** [comment]
Resolved. using the below command.

```bash
npm install jetifier --save-dev
npx jetify
npx cap sync
```
