### ISSUE TITLE
bug: Capacitor crashing when Webview Version is "Developer Build"

### ISSUE THREAD

**Issue by malua** [ionic-team/capacitor#6144]
### Capacitor Version

```
  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0
```

### Platform(s)
Android

### Current Behavior
Recently I noticed some crashes in our error tracking tool. It seems like that some Webviews return "Developer Build" for their Build Version, which causes a crash when it's converted to an Integer in Bridge.java

```
java.lang.NumberFormatException: For input string: "Developer Build"
  android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2795)
  android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2873)
  android.app.ActivityThread.-wrap11 (Unknown source)
  android.app.ActivityThread$H.handleMessage (ActivityThread.java:1603)
  android.os.Handler.dispatchMessage (Handler.java:106)
  android.os.Looper.loop (Looper.java:164)
  android.app.ActivityThread.main (ActivityThread.java:6536)
  java.lang.reflect.Method.invokeImpl (Unknown source)
  java.lang.reflect.Method.invoke (Method.java:411)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:468)
  com.android.internal.os.ZygoteInit.main (ZygoteInit.java:808)
java.lang.NumberFormatException: For input string: "Developer Build"
  java.lang.Integer.parseInt (Integer.java:617)
  java.lang.Integer.parseInt (Integer.java:656)
  com.getcapacitor.Bridge.isMinimumWebViewInstalled (Bridge.java:323)
  com.getcapacitor.Bridge.loadWebView (Bridge.java:292)
  com.getcapacitor.Bridge.<init> (Bridge.java:208)
  com.getcapacitor.Bridge.<init> (Unknown source)
  com.getcapacitor.Bridge$Builder.create (Bridge.java:1449)
  com.getcapacitor.BridgeActivity.load (BridgeActivity.java:43)
  com.getcapacitor.BridgeActivity.onCreate (BridgeActivity.java:37)
  com.classiccard.app.MainActivity.onCreate (MainActivity.java:12)
  android.app.Activity.performCreate (Activity.java:7028)
  android.app.Activity.performCreate (Activity.java:7019)
  android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1219)
  android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2748)
  android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2873)
  android.app.ActivityThread.-wrap11 (Unknown source)
  android.app.ActivityThread$H.handleMessage (ActivityThread.java:1603)
  android.os.Handler.dispatchMessage (Handler.java:106)
  android.os.Looper.loop (Looper.java:164)
  android.app.ActivityThread.main (ActivityThread.java:6536)
  java.lang.reflect.Method.invokeImpl (Unknown source)
  java.lang.reflect.Method.invoke (Method.java:411)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:468)
  com.android.internal.os.ZygoteInit.main (ZygoteInit.java:808)
```

### Expected Behavior
This error should be catched.

**Comment by jcesarmobile** [comment]
Do you get any other information about the devices where the app crashed? 
Like Android version, device vendor, etc.

**Comment by malua** [comment]
Yes i do have some more information. It seems to only happen on a specific device right now:

Android: 8.1.0
Device: Huawei Enjoy 9s

**Comment by Nikhil1920** [comment]
I saw the same error

Device
Brand:MStar
Model:SIRAGON
Orientation: Landscape
RAM free: 316.2 MB
Disk free: 1.02 GB

Operating system
Version:Android 8.0.0
Orientation: Landscape
Rooted:Yes

**Comment by RRGT19** [comment]
I have the same error:

Device: vivo S1
Android: 8.1.0

**Comment by Ezyger** [comment]
I had the same error as @RRGT19 and on the same device.

![image](https://user-images.githubusercontent.com/47608839/235516482-1b2d3459-509f-4067-b958-6a8d1f93152f.png)

**Comment by davidkroeg** [comment]
We had the same issue:
- Device: Huawei Enjoy 9s
- OS: Android 8.1.0
- @capacitor/android: ^4.0.0
- @capacitor/app: ^4.0.0

![Bildschirm­foto 2023-05-12 um 09 49 13](https://github.com/ionic-team/capacitor/assets/28301042/4c0754c0-a25c-4144-937f-2ead27788e5c)

**Comment by minajacob** [comment]
I had the same issue on two devices right now
1. **Vivo S1** (_Android 8.1.0_)
2. **Xiaomi Mi 9X** (_Android 8.1.0_)

I'm using:
@capacitor/cli: _5.0.3_
@capacitor/android: _5.0.3_
@capacitor/core: _5.0.3_

![image](https://github.com/ionic-team/capacitor/assets/6568103/66e29c28-738e-489f-81aa-089f0ca9cbc3)
![image](https://github.com/ionic-team/capacitor/assets/6568103/17464f4a-bd8e-4730-a986-ee49ecd3fbc5)

**Comment by ucoachuBunty** [comment]
Same issue seen on multiple devices @ionic-team @mlynch 

We are using:
@capacitor/android: 5.0.3
@capacitor/core: 5.0.3

Impacted OS/Devices:
OS version: android8.1.0
Model: Samsung Galaxy A70

OS version: android8.1.0
Model: Mi 9X

OS version: android8.1.0
Model: Vivo S1

OS version: android8.1.0
Model: Motorola One Vision

OS version: android8.1.0
Model: Huawei Enjoy 9s

Stack trace
`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{}: java.lang.NumberFormatException: For input string: "Developer Build"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2795)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6536)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)`

`Caused by java.lang.NumberFormatException: For input string: "Developer Build"
       at java.lang.Integer.parseInt(Integer.java:617)
       at java.lang.Integer.parseInt(Integer.java:656)
       at com.getcapacitor.Bridge.isMinimumWebViewInstalled(Bridge.java:327)
       at com.getcapacitor.Bridge.loadWebView(Bridge.java:296)
       at com.getcapacitor.Bridge.<init>(Bridge.java:212)
       at com.getcapacitor.Bridge.<init>()
       at com.getcapacitor.Bridge$Builder.create(Bridge.java:1506)
       at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:43)
       at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:37)
       at com.ucoachugolf.UcoachUgolf.MainActivity.onCreate(MainActivity.java:12)
       at android.app.Activity.performCreate(Activity.java:7028)
       at android.app.Activity.performCreate(Activity.java:7019)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2748)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6536)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)`

**Comment by nachoalcazar** [comment]
Same issue in Android 8.1.0 systems

**Comment by daniel-zero** [comment]
I added a workaround to handle this error for our users but it is not ideal of course

```java
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
      @Override
      public void uncaughtException(Thread thread, Throwable throwable) {
        FirebaseCrashlytics crashlytics = FirebaseCrashlytics.getInstance();
        if (throwable instanceof NumberFormatException) {
          crashlytics.recordException(throwable);
        } else {
          throw new RuntimeException(throwable);
        }
      }
    });
  }
```

**Comment by AntonioJABV** [comment]
Same here:

```log
Caused by java.lang.NumberFormatException: For input string: "Developer Build"
       at java.lang.Integer.parseInt(Integer.java:617)
       at java.lang.Integer.parseInt(Integer.java:656)
       at com.getcapacitor.Bridge.isMinimumWebViewInstalled(Bridge.java:299)
       at com.capacitorjs.plugins.splashscreen.SplashScreenPlugin.load(SplashScreenPlugin.java:21)
       at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:115)
       at com.getcapacitor.PluginHandle.load(PluginHandle.java:105)
       at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
       at com.getcapacitor.Bridge.registerPlugin(Bridge.java:638)
       at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:594)
       at com.getcapacitor.Bridge.<init>(Bridge.java:213)
       at com.getcapacitor.Bridge$Builder.create(Bridge.java:1513)
       at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:42)
       at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:36)
       at net.zamnesia.shroomcalculator.MainActivity.onCreate(MainActivity.java:69)
       at android.app.Activity.performCreate(Activity.java:7028)
       at android.app.Activity.performCreate(Activity.java:7019)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2748)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6536)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)
```

**Comment by mariusbolik** [comment]
I am still facing this error with @capacitor/android@5.4.1
Phone: Umidigi One with Android 8.1.0

```bash
FATAL EXCEPTION: main
Process: com.myapp.app, PID: 21013
java.lang.RuntimeException: Unable to stop activity {com.myapp.app/com.myapp.app.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4062)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4111)
	at android.app.ActivityThread.-wrap24(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1646)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
Caused by: java.lang.NullPointerException
	at com.onesignal.session.internal.session.impl.SessionService.getScheduleBackgroundRunIn(SessionService.kt:44)
	at com.onesignal.core.internal.background.impl.BackgroundManager.scheduleBackground(BackgroundManager.kt:96)
	at com.onesignal.core.internal.background.impl.BackgroundManager.onUnfocused(BackgroundManager.kt:88)
	at com.onesignal.core.internal.application.impl.ApplicationService$handleLostFocus$1.invoke(ApplicationService.kt:325)
	at com.onesignal.core.internal.application.impl.ApplicationService$handleLostFocus$1.invoke(ApplicationService.kt:325)
	at com.onesignal.common.events.EventProducer.fire(EventProducer.kt:43)
	at com.onesignal.core.internal.application.impl.ApplicationService.handleLostFocus(ApplicationService.kt:325)
	at com.onesignal.core.internal.application.impl.ApplicationService.onActivityStopped(ApplicationService.kt:184)
	at android.app.Application.dispatchActivityStopped(Application.java:234)
	at android.app.Activity.onStop(Activity.java:1862)
	at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:369)
	at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:257)
	at com.getcapacitor.BridgeActivity.onStop(BridgeActivity.java:98)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1375)
	at android.app.Activity.performStop(Activity.java:7205)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4059)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4111) 
	at android.app.ActivityThread.-wrap24(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1646) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:164) 
	at android.app.ActivityThread.main(ActivityThread.java:6523) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865) 

```

**Comment by jcesarmobile** [comment]
That's a totally different issue, the problem on this issue was a `NumberFormatException`, while you are facing a  `NullPointerException` inside some onesignal class

**Comment by Ezyger** [comment]
![image](https://github.com/ionic-team/capacitor/assets/47608839/349869e9-3172-4a88-8e8c-34c58b189586)


Now the problem happens on Samsung.

**Comment by jcesarmobile** [comment]
the fix was added in 5.4.1, you are in 5.4.0
