### ISSUE TITLE
bug: SvelteKit: Using methods in the @capacitor/app plugin fails the build

### ISSUE THREAD

**Issue by SiNONiMiTY** [ionic-team/capacitor#6268]
### Capacitor Version

```
Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2
```

### Platform(s)

```
Web - happens during build/compilation of the Svelte App
```

### Current Behavior

```
Returns this error when running the the app via the dev command

  <PROJECT>/node_modules/.pnpm/@capacitor+app@4.1.1_@capacitor+core@4.6.2/node_modules/@capacitor/app/dist/plugin.cjs.js:26
          document.addEventListener( 'visibilitychange', this.handleVisibilityChange, false )
          ^
  
  ReferenceError: document is not defined
      at new AppWeb (<PROJECT>/node_modules/.pnpm/@capacitor+app@4.1.1_@capacitor+core@4.6.2/node_modules/@capacitor/app/dist/plugin.cjs.js:26:9)
      at <PROJECT>/node_modules/.pnpm/@capacitor+app@4.1.1_@capacitor+core@4.6.2/node_modules/@capacitor/app/dist/plugin.cjs.js:8:80
      at async loadPluginImplementation (<PROJECT>/node_modules/.pnpm/@capacitor+core@4.6.2/node_modules/@capacitor/core/dist/index.cjs.js:159:47)
```

### Expected Behavior

```
App can be run or built successfully
```

### Code Reproduction

```
- Create a new SvelteKit app using the official template
- Install all the needed Capacitor packages stated on the document + @capacitor/app plugin
- Install @sveltejs/adapter-static so that we will have a static page output
- Modify svelte.config.js to use the static adapter instead of auto
- Add this code on your src/routes/+layout.ts file

  import { App } from '@capacitor/app'
  
  App.addListener( 'backButton', ( { canGoBack } ) => {
      if ( !canGoBack ) {
          App.exitApp()
      } else {
          window.history.back()
      }
  } )

  export const prerender = true;

- Now run the dev command or build
```

See the StackBlitz project for reproduction
https://stackblitz.com/edit/node-nq9kjr?file=my-app/src/routes/+layout.ts

### Other Technical Details

Commenting out the code
`document.addEventListener( 'visibilitychange', this.handleVisibilityChange, false )`
On line 26 of  node_modules/@capacitor/app/dist/plugin.cjs.js
makes the app work, and the backButton interception works when compiled as a native app

**Comment by SiNONiMiTY** [comment]
Can we add a check on the constructor logic that we should only use `document` if it is defined?

https://github.com/ionic-team/capacitor-plugins/blob/fba34b823e60aba43f82761bf7c3b42675702b7f/app/src/web.ts#L8
```
if (typeof document !== 'undefined') {
    document.addEventListener(
      'visibilitychange',
      this.handleVisibilityChange,
      false,
    );
}
```

**Comment by SiNONiMiTY** [comment]
A workaround I have found is to add a check on the code before calling the methods of AppPlugin

```
import { browser } from '$app/environment'

if ( browser ) {
    CapacitorApp.addListener( 'backButton', ( { canGoBack } ) => {
        if ( !canGoBack ) {
            CapacitorApp.exitApp()
        } else {
            window.history.back()
        }
    } )
}
```

**Comment by SiNONiMiTY** [comment]
It seems that I was putting the listener code on the wrong place,

Placing it inside the src/hooks.client.ts file gets rid of the error

Closing this issue
