### ISSUE TITLE
bug: Android Network Inspector not able to intercept requests when using http plugin

### ISSUE THREAD

**Issue by lemonrecognize** [ionic-team/capacitor#6283]
### Capacitor Version

```
@capacitor/cli: 4.6.3
@capacitor/android: 4.6.3
@capacitor/core: 4.6.3
@capacitor/ios: 4.6.3
```

### Platform(s)

Android

### Current Behavior

When using Network Inspector in Android studio, HTTP plugin throws an error.

```
E/Capacitor/Plugin: lateinit property interceptedResponse has not been initialized
    com.android.tools.idea.kotlin.UninitializedPropertyAccessException: lateinit property interceptedResponse has not been initialized
        at com.android.tools.appinspection.network.httpurl.TrackedHttpURLConnection.getHeaderFields(TrackedHttpURLConnection.kt:337)
        at com.android.tools.appinspection.network.httpurl.HttpsURLConnectionWrapper.getHeaderFields(HttpsURLConnectionWrapper.kt:189)
        at com.getcapacitor.plugin.util.CapacitorHttpUrlConnection.getHeaderFields(CapacitorHttpUrlConnection.java:329)
        at com.getcapacitor.plugin.util.HttpRequestHandler.buildResponseHeaders(HttpRequestHandler.java:283)
        at com.getcapacitor.plugin.util.HttpRequestHandler.buildResponse(HttpRequestHandler.java:209)
        at com.getcapacitor.plugin.util.HttpRequestHandler.request(HttpRequestHandler.java:405)
        at com.getcapacitor.plugin.CapacitorHttp$1.run(CapacitorHttp.java:34)
```

### Expected Behavior

Android's Network Inspector is able to intercept network traffic

**Comment by washowasho** [comment]
chrome://inspect while the app is running in Android Studio seems to be a suitable workaround (or maybe even proper alternative?).

**Comment by lemonrecognize** [comment]
> chrome://inspect while the app is running in Android Studio seems to be a suitable workaround (or maybe even proper alternative?).

As requests that are made through native API do not appear in network tab of chrome developers tools, at best with it (at least as far as I'm aware) we can check console.log statements made either by plugin or added by ourselves.

Either way, thank you for suggesting.
