### ISSUE TITLE
bug: 4.7.0 - TypeError: existingElement.children is not iterable

### ISSUE THREAD

**Issue by JumBay** [ionic-team/capacitor#6321]
### Capacitor Version

```
$ npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0
  @capacitor/core: 4.7.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

Since capacitor@4.7.0 when building the android app, I got this error:
```txt
✔ copy android in 2.29s
[fatal] TypeError: existingElement.children is not iterable
```
Full error

```txt
✔ Copying web assets from www to android/app/src/main/assets/public in 1.79s
✔ Creating capacitor.config.json in android/app/src/main/assets in 32.38ms
⠧ copy android [info] Found 14 Cordova plugins for android:
       com-darryncampbell-cordova-plugin-intent@2.2.0
       cordova-plugin-advanced-http@3.3.1
       cordova-plugin-background-mode@0.7.3
       cordova-plugin-chromecast@1.0.0
       cordova-plugin-device@2.1.0
       cordova-plugin-file@6.0.2
       cordova-plugin-media@5.0.4-dev
       cordova-plugin-nativestorage@2.3.2
       cordova-plugin-purchase@11.0.0
       cordova-plugin-screen-orientation@3.0.2
       cordova-plugin-zeroconf@1.4.2
       cordova-simple-volume@1.0.4
       cordova-sqlite-storage@6.1.0
       es6-promise-plugin@4.2.2
✔ copy android in 2.29s
[fatal] TypeError: existingElement.children is not iterable
    at doesElementMatch (/Users/jb/project/node_modules/@capacitor/cli/dist/cordova.js:699:99)
    at doesElementMatch (/Users/jb/project/node_modules/@capacitor/cli/dist/cordova.js:686:88)
    at doesXmlManifestContainRequiredInfo (/Users/jb/project/node_modules/@capacitor/cli/dist/cordova.js:740:65)
    at /Users/jb/project/node_modules/@capacitor/cli/dist/cordova.js:752:38
✔ Copying web assets from www to ios/App/App/public in 1.70s
✔ Creating capacitor.config.json in ios/App/App in 919.32μs
⠴ copy ios [info] Found 13 Cordova plugins for ios:
       cordova-plugin-advanced-http@3.3.1
       cordova-plugin-background-mode@0.7.3
       cordova-plugin-chromecast@1.0.0
       cordova-plugin-device@2.1.0
       cordova-plugin-file@6.0.2
       cordova-plugin-media@5.0.4-dev
       cordova-plugin-nativestorage@2.3.2
       cordova-plugin-purchase@11.0.0
       cordova-plugin-screen-orientation@3.0.2
       cordova-plugin-zeroconf@1.4.2
       cordova-simple-volume@1.0.4
       cordova-sqlite-storage@6.1.0
       es6-promise-plugin@4.2.2
✔ copy ios in 1.95s
✔ copy web in 27.83ms
``` 

### Other Technical Details

`npm --version` output: 8.19.2

`node --version` output: v18.12.1

**Comment by JumBay** [comment]
Here is the a repository with the issue, it uses the same cordova plugins that I use.

If you remove these lines from https://github.com/JumBay/ionic-capacitor-issue-6321/blob/main/android/app/src/main/AndroidManifest.xml#L28 it works, but the plugin asks to add them:
```xml
          <intent-filter>
            <action android:name="com.darryncampbell.cordova.plugin.intent.ACTION"/>
            <category android:name="android.intent.category.DEFAULT"/>
          </intent-filter>
