### ISSUE TITLE
Plugin-cordova-opentok (opentok.js) on android not working

### ISSUE THREAD

**Issue by csarglue** [ionic-team/capacitor#635]
I have a project to which I added the plugin-cordova-opentok using opentok.js (I need it for the ios version). When you start the app on an android, it generates the following error:

`java.lang.ClassNotFoundException: com.tokbox.cordova.OpenTokAndroidPlugin

      at java.lang.Class.classForName(Native Method)
      at java.lang.Class.forName(Class.java:309)
      at java.lang.Class.forName(Class.java:273)
      at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
      at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
      at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
      at org.apache.cordova.PluginManager.init(PluginManager.java:86)
      at com.getcapacitor.cordova.MockCordovaWebViewImpl.init(MockCordovaWebViewImpl.java:54)
      at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:70)
      at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:54)
      at com.cliniweb.chat.patient.MainActivity.onCreate(MainActivity.java:16)
      at android.app.Activity.performCreate(Activity.java:6010)
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
      at android.app.ActivityThread.access$800(ActivityThread.java:155)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:135)
      at android.app.ActivityThread.main(ActivityThread.java:5343)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)`

**Comment by jcesarmobile** [comment]
I can't reproduce the issue with latest version.
Make sure you run `npx cap sync` or `npx cap update` after installing the plugin, that should copy `com.tokbox.cordova.OpenTokAndroidPlugin.java` to the proper location.

**Comment by ramseyfeng** [comment]
@jcesarmobile Hi, may I ask if you have capacitor worked with opentok successfully?
