### ISSUE TITLE
bug: deploying app to physical iOS device failed!

### ISSUE THREAD

**Issue by Lyfei** [ionic-team/capacitor#6392]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/android: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS

### Current Behavior

Deploying iOS  failed!

```
$ ionic capacitor run ios --no-build
? Which device would you like to target? iphone-12 (00008101-001D31D63E01001E)
> capacitor run ios --target 00008101-001D31D63E01001E
...
[capacitor] ✔ Updating iOS native dependencies with pod install in 7.08s
[capacitor] ✔ update ios in 7.65s
[capacitor] ✔ Running xcodebuild in 25.32s
[capacitor] ✖ Deploying App.app to 00008101-001D31D63E01001E - failed!
[capacitor] [error] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 47. Received 48
[capacitor]         at boundsError (internal/buffer.js:72:9)
[capacitor]         at writeU_Int8 (internal/buffer.js:727:5)
[capacitor]         at Buffer.writeUInt8 (internal/buffer.js:734:10)
[capacitor]         at toCString (.../ionic-demos/node_modules/native-run/dist/ios/lib/client/afc.js:162:9)
[capacitor]         at AFCClient.openFile (.../ionic-demos/node_modules/native-run/dist/ios/lib/client/afc.js:52:9)
[capacitor]         at AFCClient.uploadFile (.../ionic-demos/node_modules/native-run/dist/ios/lib/client/afc.js:74:24)
```

Deploying to simulator is ok
```
$ ionic capacitor run ios --no-build
? Which device would you like to target? Used 8P (simulator) (22366F41-F4A6-451D-B460-6E70C9326ED9)
> capacitor run ios --target 22366F41-F4A6-451D-B460-6E70C9326ED9
...
[capacitor] ✔ Updating iOS native dependencies with pod install in 8.29s
[capacitor] ✔ update ios in 8.70s
[capacitor] ✔ Running xcodebuild in 95.50s
[capacitor] ✔ Deploying App.app to 22366F41-F4A6-451D-B460-6E70C9326ED9 in 48.71s
```

### Expected Behavior

work well

**Comment by jcesarmobile** [comment]
is the phone connected using a USB cable or using wifi debugging?

**Comment by Lyfei** [comment]
> is the phone connected using a USB cable or using wifi debugging?

Use USB cable。If you do not connect, you will not see the device in the terminal。

**Comment by markemer** [comment]
Can you build it to your device using Xcode after running `npx cap open ios`?

**Comment by Lyfei** [comment]
> Can you build it to your device using Xcode after running `npx cap open ios`?

yes，I can

**Comment by markemer** [comment]
> > Can you build it to your device using Xcode after running `npx cap open ios`?
> 
> yes，I can

Ok, does a fresh project work? Also, can you post sample project that still breaks?

**Comment by Lyfei** [comment]
> > > Can you build it to your device using Xcode after running `npx cap open ios`?
> > 
> > 
> > yes，I can
> 
> Ok, does a fresh project work?

work well

**Comment by markemer** [comment]
Ok @Lyfei, so I think we need to figure out what about your specific setup is different. Strange that Xcode works, and fresh project works.
