### ISSUE TITLE
ClassNotFoundException com.plugin.gcm.OneSignalPush

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/capacitor#647]
Installed cordova plugin onesignal-cordova-plugin (now working on capacitor 1.0.0-beta.1):
```
npm install onesignal-cordova-plugin
npx cap sync
```

Build app and open Android Studio:
```
ionic build
npx cap copy
npx cap open android
```

Add code as per Ionic setup instructions:
https://documentation.onesignal.com/docs/ionic-sdk-setup

Run app in Android Studio. Logcat shows the following errors:

```
07-11 07:08:26.134 8462-8506/com.myappname.app I/console: onscript loading complete
07-11 07:08:28.284 8462-8506/com.myappname.app I/console: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
07-11 07:08:28.464 8462-8506/com.myappname.app I/console: Ionic Native: deviceready event fired after 1034 ms
07-11 07:08:28.474 8462-8506/com.myappname.app I/console: Native: tried calling StatusBar.styleDefault, but the StatusBar plugin is not installed.
07-11 07:08:28.474 8462-8506/com.myappname.app I/console: Install the StatusBar plugin: 'ionic cordova plugin add cordova-plugin-statusbar'
07-11 07:08:28.474 8462-8506/com.myappname.app I/console: Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed.
07-11 07:08:28.484 8462-8506/com.myappname.app I/console: Install the SplashScreen plugin: 'ionic cordova plugin add cordova-plugin-splashscreen'
07-11 07:08:28.484 8462-8506/com.myappname.app I/console: oneSignal {}
07-11 07:08:28.494 8462-8534/com.myappname.app W/System.err: java.lang.ClassNotFoundException: com.plugin.gcm.OneSignalPush
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:308)
        at java.lang.Class.forName(Class.java:272)
        at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:73)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.plugin.gcm.OneSignalPush" on path: DexPathList[[zip file "/data/app/com.myappname.app-1/base.apk", zip file "/data/app/com.myappname.app-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    	... 13 more
    	Suppressed: java.lang.ClassNotFoundException: com.plugin.gcm.OneSignalPush
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
    		... 14 more
    	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
07-11 07:08:28.494 8462-8534/com.myappname.app I/System.out: Error adding plugin com.plugin.gcm.OneSignalPush.
07-11 07:08:28.494 8462-8534/com.myappname.app E/Capacitor: Post message error:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:73)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-11 07:08:28.494 8462-8506/com.myappname.app I/console: before
07-11 07:08:28.504 8462-8534/com.myappname.app W/System.err: java.lang.ClassNotFoundException: com.plugin.gcm.OneSignalPush
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:308)
        at java.lang.Class.forName(Class.java:272)
        at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:73)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.plugin.gcm.OneSignalPush" on path: DexPathList[[zip file "/data/app/com.myappname.app-1/base.apk", zip file "/data/app/com.myappname.app-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    	... 13 more
    	Suppressed: java.lang.ClassNotFoundException: com.plugin.gcm.OneSignalPush
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
    		... 14 more
    	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
07-11 07:08:28.504 8462-8534/com.myappname.app I/System.out: Error adding plugin com.plugin.gcm.OneSignalPush.
07-11 07:08:28.504 8462-8534/com.myappname.app E/Capacitor: Post message error:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:73)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-11 07:08:28.504 8462-8534/com.myappname.app W/System.err: java.lang.ClassNotFoundException: com.plugin.gcm.OneSignalPush
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:308)
        at java.lang.Class.forName(Class.java:272)
        at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:73)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.plugin.gcm.OneSignalPush" on path: DexPathList[[zip file "/data/app/com.myappname.app-1/base.apk", zip file "/data/app/com.myappname.app-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    	... 13 more
    	Suppressed: java.lang.ClassNotFoundException: com.plugin.gcm.OneSignalPush
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
    		... 14 more
    	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
07-11 07:08:28.504 8462-8534/com.myappname.app I/System.out: Error adding plugin com.plugin.gcm.OneSignalPush.
07-11 07:08:28.504 8462-8534/com.myappname.app E/Capacitor: Post message error:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:73)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-11 07:08:28.514 8462-8534/com.myappname.app W/System.err: java.lang.ClassNotFoundException: com.plugin.gcm.OneSignalPush
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:308)
        at java.lang.Class.forName(Class.java:272)
        at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:73)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.plugin.gcm.OneSignalPush" on path: DexPathList[[zip file "/data/app/com.myappname.app-1/base.apk", zip file "/data/app/com.myappname.app-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.myappname.app-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    	... 13 more
    	Suppressed: java.lang.ClassNotFoundException: com.plugin.gcm.OneSignalPush
07-11 07:08:28.524 8462-8534/com.myappname.app W/System.err:     at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
    		... 14 more
    	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
07-11 07:08:28.524 8462-8534/com.myappname.app I/System.out: Error adding plugin com.plugin.gcm.OneSignalPush.
07-11 07:08:28.524 8462-8534/com.myappname.app E/Capacitor: Post message error:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:73)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-11 07:08:28.524 8462-8506/com.myappname.app I/console: after
07-11 07:08:28.974 8462-8462/com.myappname.app E/ViewRootImpl: sendUserActionEvent() mView == null
```

**Comment by jcesarmobile** [comment]
Looks like it doesn't find the native classes.
Can you try running `npx cap sync` again?

I've build a sample project and it's working fine
BTW, I used master code, the changes I made are not in beta 1, but the changes were about the AndroidManifest.xml complaining, so shouldn't cause this problem.

**Comment by matthew-valenti** [comment]
Thanks! Might be a version issue then. Will start new project from scratch and try again. Currently getting "error must not undeclare prefix" (which was resolved by upgrading to latest version of capacitor) but now unable to recover from it. OneSignal is working on iOS.

**Comment by jcesarmobile** [comment]
The version with the fix has not been released yet.
Good to know that it works on iOS.

**Comment by matthew-valenti** [comment]
Thanks for clarification. I thought this fix had been released:
https://github.com/ionic-team/capacitor/issues/637
I'll wait for the next release and then continue testing.

**Comment by jcesarmobile** [comment]
Going to close for now, if you can reproduce on next release, please reopen.
