### ISSUE TITLE
bug: `npx cap sync` fails the pod install step:

### ISSUE THREAD

**Issue by BenRacicot** [ionic-team/capacitor#6505]
### Capacitor Version
```
npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

### Platform(s)
iOS

### Current Behavior
`npx cap sync` on a _previously_ running project suddenly fails the pod install step:

```
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/user_interface/error_report.rb:34:in
        `force_encoding': can't modify frozen String (FrozenError)
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/user_interface/error_report.rb:34:in
        `report'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:66:in `report_error'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:396:in `handle_exception'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:337:in `rescue in run'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:324:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:52:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/bin/pod:55:in `<top (required)>'
        from /usr/local/bin/pod:23:in `load'
        from /usr/local/bin/pod:23:in `<main>'
        /Library/Ruby/Gems/2.6.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:284:in `raise_parser_error': [!] Unexpected
        end of string while parsing (Nanaimo::Reader::ParseError)
        #  -------------------------------------------
        1>
        ^
        #  -------------------------------------------
        from /Library/Ruby/Gems/2.6.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:130:in `parse_object'
        from /Library/Ruby/Gems/2.6.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:107:in `parse!'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:211:in `initialize_from_file'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:113:in `open'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1194:in `block (2
        levels) in inspect_targets_to_integrate'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1193:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1193:in `block in
        inspect_targets_to_integrate'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1188:in
        `inspect_targets_to_integrate'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:107:in `analyze'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:422:in `analyze'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:244:in `block in
        resolve_dependencies'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:162:in `install!'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/command/install.rb:52:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:52:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/bin/pod:55:in `<top (required)>'
        from /usr/local/bin/pod:23:in `load'
        from /usr/local/bin/pod:23:in `<main>'
```

### Expected Behavior
The iOS folder should sync code changes and the project is then ready to open in Xcode.

### Other Technical Details

`npm --version` output: `8.19.2`

`node --version` output: `v18.12.1`

`pod --version` output (iOS issues only): `1.12.0`

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by markemer** [comment]
Real quick question. Did you update to Xcode 16.4 recently?

**Comment by BenRacicot** [comment]
Hi @markemer yeah this was absolutely **associated** or **in-addition** to https://github.com/ionic-team/capacitor/issues/6457#event-9045440379

But after using the workaround (before Cocoapods fix) the issue disappeared.

**Comment by markemer** [comment]
So is this working for you now with the latest cocoapods? Or did it come back?

**Comment by BenRacicot** [comment]
It is working now after the cocoapods change.

**Comment by markemer** [comment]
Awesome - closing this then.

**Comment by RenzoPH** [comment]
Hi, anyone are experience these issue? currently these is the issue that we encounter in our pipeline to generate an ipa file

Processing Info.plist

▸ Running script ‘[CP] Embed Pods Frameworks’

▸ Generating ‘App.app.dSYM’

** ARCHIVE FAILED **

The following build commands failed:

PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/runner/Library/Developer/Xcode/DerivedData/App-azlyibamtvkrbhfwntgmcwffjqtw/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/App.build/Release-iphoneos/App.build/Script-9592DBEFFC6D2A0C8D5DEB22.sh (in target ‘App’ from project ‘App’)

(1 failure)
