### ISSUE TITLE
bug: Usage of Cookie Plugin causes app crashes on Android

### ISSUE THREAD

**Issue by daniel-zero** [ionic-team/capacitor#6640]
### Capacitor Version

```
    "@capacitor/app": "^5.0.2",
    "@capacitor/core": "^5.0.3",
    "@capacitor/device": "^5.0.2",
    "@capacitor/haptics": "5.0.2",
    "@capacitor/keyboard": "5.0.2",
    "@capacitor/status-bar": "5.0.2",
```

### Platform(s)
- Android

### Current Behavior

When calling any capacitor CookiePlugin method the app will crash
```log
 Serious error executing plugin
                                                                                                    java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:780)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.plugin.CapacitorCookieManager.removeAllCookies()' on a null object reference
                                                                                                    	at com.getcapacitor.plugin.CapacitorCookies.clearAllCookies(CapacitorCookies.java:150)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:780) 
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
```

### Expected Behavior

The plugin call should work as expected

### Code Reproduction

Create a new capacitor project with Angular & Ionic and call any Capacitor Cookie plugin method

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by daniel-zero** [comment]
@jcesarmobile I checked the changes made to the Cookie plugin in v5. Since the initialisation of the plugin is now made in the `isEnabled` method, the plugin is not getting initialised.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by MaximeEvangeliste** [comment]
I also get that problem. Whenever I enable the capacitor cookie plugin on iOS everything works but the same functionality crashes on Android. I get a java execution error. You think it could be related to my java version? Is there a recommended version we should be using when developing on Android with capacitor?

**Comment by daniel-zero** [comment]
The problem is that the cookie plugin has to be enabled so it can be used but when you want to use it just with the http plugin to download a file that requires a specific cookie, it will break @jcesarmobile. Can this behaviour achieved without enabling the plugin in the `capacitor.config.ts` file? Otherwise it is currently not possible to upgrade to capacitor v4.8 or v5 without breaking our apps behaviours

**Comment by jcesarmobile** [comment]
Can you please provide a sample app that reproduces the issue?

**Comment by daniel-zero** [comment]
@jcesarmobile Sure, hiere is the repo: https://github.com/daniel-zero/capacitor-bug-6640

Just take a look into the `app.component.ts` file. As you can see, I'm calling the Cookies-Plugin without enabling the Plugin globally. 


```ts
  ngOnInit(): void {
    CapacitorCookies.setCookie({
      key: 'test',
      value: 'test',
      url: 'https://www.google.com',
    });
  }
```

Start the app in the android emulator and the app will crash directly with the documented error

```log
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.plugin.CapacitorCookieManager.setCookie(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)' on a null object reference

```

**Comment by jcesarmobile** [comment]
Can you explain your use case a bit better?

How do you download the document with the cookie you added? If you don't enable the cookies plugin, then webview connections won't use that cookie, are you using native connections like using http plugin?

**Comment by daniel-zero** [comment]
Sure, here is the code on our side where we are using the cookie plugin to authenticate the user do be able to download one secured file using the capacitor http plugin (this.http is just a reference to the capacitor http plugin)

```ts
...

  private http: CapacitorHttpPlugin;

  constructor() {
    if (Capacitor.isPluginAvailable('CapacitorHttp')) {
      this.http = CapacitorHttp;
    }
  }
...

public downloadFile(
    url: string,
    targetFile: string,
    // eslint-disable-next-line @typescript-eslint/ban-types
    headers: {},
    authToken?: string
  ): Promise<WriteFileResult> {
    return CapacitorCookies.clearCookies({ url })
      .then(() => {
        if (authToken) {
          return CapacitorCookies.setCookie({
            url,
            key: '__i',
            value: authToken,
          });
        } else {
          return Promise.resolve();
        }
      })
      .then(() => {
        return this.http
          .get({
            url,
            headers,
            responseType: 'blob',
          })
          .then(({ data }) => {
            return Filesystem.writeFile({
              data,
              directory: Directory.Cache,
              path: targetFile,
            });
          });
      });
  }
```

**Comment by jcesarmobile** [comment]
thanks, we were discussing if we should set the default cookie manager to use the plugin cookie manager when the plugin is not enabled or only if do it if the plugin is enabled, but I think not setting it would break your use case.
chace already sent a PR that set the default cookie manager even if the plugin is not enabled, so that should fix your issue.
