### ISSUE TITLE
bug: App crashes with error - Using WebView from more than one process at once with the same data directory is not supported

### ISSUE THREAD

**Issue by justinpathrose** [ionic-team/capacitor#6709]
### Capacitor Version

```
  @capacitor/cli: 5.1.0
  @capacitor/core: 5.1.0
  @capacitor/android: 5.1.0
  @capacitor/ios: 5.1.0

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4
```

### Platform(s)
Android versions 9, 12, 11 and 10

### Current Behavior

App crashes in production and few users are unable to use the app even after uninstalling and installing again. We are uable to replicate the issue on the devices which we see are getting affected.

The error seems to have started with this exception - **Caused by java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377**, which suggests that the app has more than 1 process running and hence not able to access webview data directory. 

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{<>.MainActivity}: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class com.getcapacitor.CapacitorWebView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

Caused by android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class com.getcapacitor.CapacitorWebView


Caused by android.view.InflateException: Binary XML file line #13: Error inflating class com.getcapacitor.CapacitorWebView


Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
       at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:27)
       at <>.MainActivity.onCreate(MainActivity.java:11)
       at android.app.Activity.performCreate(Activity.java:7327)
       at android.app.Activity.performCreate(Activity.java:7318)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

Caused by java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377

```

### Expected Behavior
App does not crash.

### Other Technical Details

`npm --version` output: 9.5.1

`node --version` output: v18.16.1

**Comment by JosefBredereck** [comment]
That may explain our issue too.
We have an AsWebauthenticationSession Plugin and the [@capacitor-community/privacy-screen](https://github.com/capacitor-community/privacy-screen) installed. And in combination, one of each will break the app or lead to a crash.

Both are somehow accessing the web view.

```
DispatchQueue.main.sync {
    let view = self.bridge?.webView?.window ?? ASPresentationAnchor()
    implementation = AsWebAuthenticationSession(forView: view)
}
```

```
DispatchQueue.main.async {
     self.bridge?.webView?.enableScreenshots()
}
```

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
