### ISSUE TITLE
bug: triggerJSEvent fails with null object reference

### ISSUE THREAD

**Issue by kimiroo** [ionic-team/capacitor#6810]
## Bug Report
I'm trying to dispatch an event from native java code to javascript environments to trigger some functions. I tried using triggerJSEvent but to no success. I tried the official documentation, code from forum but they all won't work.

### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/ios: 5.2.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.2.3
  @capacitor/android: 5.2.3
  @capacitor/core: 5.2.3

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

- triggerJSEvent fails with "Attempt to invoke virtual method 'triggerJSEvent' on a null object reference".
  ```
  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.Bridge.triggerJSEvent(java.lang.String, java.lang.String, java.lang.String)' on a null object reference
      at com.capacitor.reproduction.triggerJSEvent.TestEvent.testCall(TestEvent.java:31)
      at com.capacitor.reproduction.triggerJSEvent.TestPlugin.testRun(TestPlugin.java:24)
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
      at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:774) 
      at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
      at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
      at android.os.Handler.handleCallback(Handler.java:883) 
      at android.os.Handler.dispatchMessage(Handler.java:100) 
      at android.os.Looper.loop(Looper.java:237) 
      at android.os.HandlerThread.run(HandlerThread.java:67)
  ```

### Expected Behavior

-  triggerJSEvent should trigger an event in main window.

### Code Reproduction

Sample application: [https://github.com/kimiroo/capacitor-bug-triggerJSEvent](https://github.com/kimiroo/capacitor-bug-triggerJSEvent)

### Other Technical Details

npm version: 9.6.7

node version: v18.17.0

### Additional Context

This is my first time doing bug report. I might have missed some information. Please tell me if so.

**Comment by jcesarmobile** [comment]
You can't create Capacitor plugins with `new` keyword, Capacitor plugins are created and managed by Capacitor, creating an existing plugin with `new` keyword will result in a invalid plugin.
I've updated your sample app so the `TestEvent` class doesn't extend `Plugin` class, so it's a regular java class you can create with `new` keyword as it didn't seem that it needed to be a `Plugin` class since you are just calling that class from another `Plugin` class, and I've passed the plugin bridge to the `TestEvent` class so it can call triggerJSEvent.

https://github.com/kimiroo/capacitor-bug-triggerJSEvent/pull/1
