### ISSUE TITLE
Branch.io Cordova Plugin Error

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/capacitor#686]
Branch.io cordova plugin is working successfully in Ionic 3 + Cordova but errors in Ionic 4 + Capacitor.

ionic info
```
Ionic:

   ionic (Ionic CLI)          : 4.0.0 (C:\Users\Matthew\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0
   @angular-devkit/schematics : 0.7.0
   @angular/cli               : 6.1.0
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   NodeJS : v8.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set
```

To reproduce:
- Create Ionic 4 blank project.
- Install capacitor.
- Add branch.io plugin results in error.

```
cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=key_live_njA3NArn661H44GcbBP4dmknxEnt4IU9 --variable URI_SCHEME=ogia.app.link --save

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Adding branch-cordova-sdk to package.json
Saved plugin info for "branch-cordova-sdk" to config.xml
(node:5580) UnhandledPromiseRejectionWarning: Error: BRANCH SDK: <branch-config> tag is not set in the config.xml. Docs https://goo.gl/GijGKP
    at getBranchXml (P:\wwwroot\CymetrikCore_app\blank\plugins\branch-cordova-sdk\src\scripts\npm\processConfigXml.js:47:13)
    at Object.read (P:\wwwroot\CymetrikCore_app\blank\plugins\branch-cordova-sdk\src\scripts\npm\processConfigXml.js:16:23)
    at run (P:\wwwroot\CymetrikCore_app\blank\plugins\branch-cordova-sdk\src\scripts\hooks\afterPrepare.js:15:43)
    at runScriptViaModuleLoader (C:\Users\Matthew\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:188:18)
    at runScript (C:\Users\Matthew\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:164:16)
    at C:\Users\Matthew\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:132:20
    at _fulfilled (C:\Users\Matthew\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Matthew\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Matthew\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
    at C:\Users\Matthew\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:810:14
(node:5580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jcesarmobile** [comment]
That error is because you don't have the `<branch-config>` tag in the config.xml, not related to Capacitor.

Anyway, Capacitor doesn't use the config.xml, and the plugin has a lot of hooks that Capacitor won't run, so whatever the plugin does with that information, you should do it manually in your project.
