### ISSUE TITLE
bug: Error when attempting to run livereload on external iOS Device.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [ionic-team/capacitor#6984]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

Installed Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/ios: 5.4.2
  @capacitor/android: 5.4.2

### Platform(s)
iOS

### Current Behavior
I'm running `ionic cap run ios -l --external` and receiving the following error.
```
[capacitor] [error] Error: There was an error installing app
[capacitor]         at /Users/.../Documents/xxxxx/xxxxx/node_modules/native-run/dist/ios/lib/client/installation_proxy.js:72:24
[capacitor]         at LockdownProtocolReader.callback (/Users/xxxxx/Documents/xxxxx/xxxxx/node_modules/native-run/dist/ios/lib/protocol/protocol.js:93:21)
[capacitor]         at LockdownProtocolReader.onData (/Users/xxxxx/Documents/xxxxx/xxxxx/node_modules/native-run/dist/ios/lib/protocol/protocol.js:53:26)
[capacitor]         at Socket.emit (node:events:513:28)
[capacitor]         at addChunk (node:internal/streams/readable:315:12)
[capacitor]         at readableAddChunk (node:internal/streams/readable:289:9)
[capacitor]         at Socket.Readable.push (node:internal/streams/readable:228:10)
```

This started happening after I updated to XCode 15. If I run `ionic cap build ios` and then manually run the build from XCode it works fine. It's only an issue when trying to execute a liveReload. 

### Other Technical Details

`npm --version` output: 8.19.3

`node --version` output: v16.19.0

`pod --version` output (iOS issues only): 1.12.1

**Comment by selected-pixel-jameson** [comment]
Tried this on a device running the latest iOS version and the error didn't occur.

**Comment by selected-pixel-jameson** [comment]
When I attempt to run this on my iPhone 8 Plus running iOS version 16.7.1 it will not not work. I just get the above error. If I manually run the build through XCode it will work fine.  This is the most up to date version of iOS I can install on this device. 

I've tried adjusting my build target from 13 to 14 in the XCode project but I get the same error.

**Comment by jcesarmobile** [comment]
Might be fixed by updating to Capacitor 6 or newer as it was updated to use native-run 2.x which should support Xcode 15.

But since you are using ionic command to run it might be using a different version, so make sure you have native-run 2.x installed globally.

If the problem is still present after updating to Capacitor 6 and native-run 2.x, report a new issue in native-run repository https://github.com/ionic-team/native-run/issues
