### ISSUE TITLE
bug: All `npx cap` commands fail with `ERR_REQUIRE_ESM`

### ISSUE THREAD

**Issue by larsblumberg** [ionic-team/capacitor#7126]
### Capacitor Version

`npx cap doctor` fails for the very same reason as reported below. However here are all capacitor dependencies in `package.json`:

```
  "dependencies": {
    "@capacitor/android": "^5.5.1",
    "@capacitor/app": "^5.0.6",
    "@capacitor/core": "^5.5.1",
    "@capacitor/ios": "^5.5.1",
    ...
  },
  "devDependencies": {
    "@capacitor/assets": "^3.0.1",
    "@capacitor/cli": "^5.5.1",
    ...
  }
```

### Platform(s)

all platforms

### Current Behavior

All `npx cap` commands fail with `ERR_REQUIRE_ESM`, example:

```
❯ npx cap add android  
/home/lars/coding/capacitor_test/node_modules/@ionic/utils-terminal/dist/format.js:12
const wrapAnsi = require("wrap-ansi");
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/lars/coding/capacitor_test/node_modules/wrap-ansi/index.js from /home/lars/coding/capacitor_test/node_modules/@ionic/utils-terminal/dist/format.js not supported.
Instead change the require of index.js in /home/lars/coding/capacitor_test/node_modules/@ionic/utils-terminal/dist/format.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/lars/coding/capacitor_test/node_modules/@ionic/utils-terminal/dist/format.js:12:18)
    at Object.<anonymous> (/home/lars/coding/capacitor_test/node_modules/@ionic/utils-terminal/dist/index.js:6:22)
    at Object.<anonymous> (/home/lars/coding/capacitor_test/node_modules/@ionic/cli-framework-output/dist/index.js:5:26)
    at Object.<anonymous> (/home/lars/coding/capacitor_test/node_modules/@capacitor/cli/dist/log.js:5:32)
    at Object.<anonymous> (/home/lars/coding/capacitor_test/node_modules/@capacitor/cli/dist/config.js:10:15)
    at Object.<anonymous> (/home/lars/coding/capacitor_test/node_modules/@capacitor/cli/dist/index.js:7:18)
    at Object.<anonymous> (/home/lars/coding/capacitor_test/node_modules/@capacitor/cli/bin/capacitor:17:11) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.4.0
```

### Expected Behavior

Commands execute without `ERR_REQUIRE_ESM`

### Code Reproduction

Please excuse that I haven't yet created a simple demo repo, as I was hoping that the error message is expressive enough. Can however provide a repo if needed.

### Other Technical Details

`npm --version` output: 9.7.2

`node --version` output: v20.0.4

### Additional Context

We use TypeScript.

**Comment by oliveryasuna** [comment]
It shouldn't matter, but have you tried without `npx`? Since you have `@capacitor/cli` as a devDependency, it should be unnessary.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
