### ISSUE TITLE
[Bug]: Browser.open with url tel: or whatsap: throws fatal exception on any version of Android

### ISSUE THREAD

**Issue by panchazo** [ionic-team/capacitor#7578]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/android: 6.1.1
  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

- Create a new angular project: `ionic start`
- Add android support: `ionic capacitor add android`
- Install Browser Capacitor: `npm install @capacitor/browser`
- Compile and run: `ionic capacitor build android --prod`
- Try to open the phone or whatsap using:     Browser.open({ url: 'tel:5555555555' });

Result: app crashes. Logcat output
```

2024-07-24 10:41:02.848 21913-21913 AndroidRuntime          io.ionic.starter                     E  FATAL EXCEPTION: main
                                                                                                    Process: io.ionic.starter, PID: 21913
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.ionic.starter/com.capacitorjs.plugins.browser.BrowserControllerActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=tel:xxxxxxxxxxxxxx pkg=com.android.chrome (has extras) }
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=tel:xxxxxxxxxxxxxx pkg=com.android.chrome (has extras) }
                                                                                                    	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2117)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1762)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5410)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5368)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:761)
                                                                                                    	at android.app.Activity.startActivity(Activity.java:5754)
                                                                                                    	at androidx.core.content.ContextCompat$Api16Impl.startActivity(ContextCompat.java:1064)
                                                                                                    	at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:322)
                                                                                                    	at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:523)
                                                                                                    	at com.capacitorjs.plugins.browser.Browser.open(Browser.java:112)
                                                                                                    	at com.capacitorjs.plugins.browser.BrowserControllerActivity.open(BrowserControllerActivity.java:43)
                                                                                                    	at com.capacitorjs.plugins.browser.BrowserPlugin.lambda$open$0(BrowserPlugin.java:72)
                                                                                                    	at com.capacitorjs.plugins.browser.BrowserPlugin.$r8$lambda$I9bLDRWh7vl57kOTAfjVKp5lWOU(Unknown Source:0)
                                                                                                    	at com.capacitorjs.plugins.browser.BrowserPlugin$$ExternalSyntheticLambda0.onControllerReady(Unknown Source:8)
                                                                                                    	at com.capacitorjs.plugins.browser.BrowserControllerActivity.onCreate(BrowserControllerActivity.java:19)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8057)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8037)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 

```

### Expected Behavior

When using Browser.open with url starting with "tel:" or "whatsap:" it should open the phone or whatsap instead of crashing the app

### Project Reproduction

https://github.com/panchazo/IntentErrorTest

**Comment by jcesarmobile** [comment]
browser plugin can only open http/https urls

There is an issue open for catching the crash and return an error instead when using urls that are not http/https
https://github.com/ionic-team/capacitor-plugins/issues/2036

**Comment by panchazo** [comment]
Is there an alternative to achieve the previous behaviour to open tel: whatsap: etc?

**Comment by jcesarmobile** [comment]
There is no "previous behaviour", this has never been supported by browser plugin.

You can app-launcher plugin to launch other apps
https://capacitorjs.com/docs/apis/app-launcher

Or anchor tags (`a`), or javascript redirections should probably work too.
