### ISSUE TITLE
Error trying to run example app on Android

### ISSUE THREAD

**Issue by cwoolum** [ionic-team/capacitor#89]
I'm trying to run the example app on android and when the app launches, it crashes immediately. Here's the relevant stack trace from logcat. Device I'm using is a Samsung Galaxy S8+ running Android 8.0. I'm compiling on Windows 10 in android Studio 3.0.

> 01-23 20:25:26.068 24749-24749/com.getcapacitor.myapp E/Capacitor: Unable to export Capacitor JS. App will not function!
                                                                   com.getcapacitor.JSExportException: Unable to load native-bridge.js. Capacitor will not function!
                                                                       at com.getcapacitor.JSExport.getCoreJS(JSExport.java:30)
                                                                       at com.getcapacitor.Bridge.getJSInjector(Bridge.java:396)
                                                                       at com.getcapacitor.Bridge.<init>(Bridge.java:125)
                                                                       at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:45)
                                                                       at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:35)
                                                                       at com.getcapacitor.myapp.MainActivity.onCreate(MainActivity.java:11)
                                                                       at android.app.Activity.performCreate(Activity.java:7174)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
                                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6938)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
                                                                    Caused by: java.io.FileNotFoundException: public/native-bridge.js
                                                                       at android.content.res.AssetManager.openAsset(Native Method)
                                                                       at android.content.res.AssetManager.open(AssetManager.java:388)
                                                                       at android.content.res.AssetManager.open(AssetManager.java:362)
                                                                       at com.getcapacitor.JSExport.getCoreJS(JSExport.java:20)
                                                                       at com.getcapacitor.Bridge.getJSInjector(Bridge.java:396) 
                                                                       at com.getcapacitor.Bridge.<init>(Bridge.java:125) 
                                                                       at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:45) 
                                                                       at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:35) 
                                                                       at com.getcapacitor.myapp.MainActivity.onCreate(MainActivity.java:11) 
                                                                       at android.app.Activity.performCreate(Activity.java:7174) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
                                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                       at android.os.Looper.loop(Looper.java:164) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6938) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
01-23 20:25:26.113 24749-24846/com.getcapacitor.myapp A/chromium: [FATAL:jni_android.cc(243)] Please include Java exception stack in crash report

**Comment by mlynch** [comment]
Appreciate the issue. We’re not quite ready for public use and this issue with be moot soon, so I’m going to close.

Stay tuned for a working example with docs soon!
