### ISSUE TITLE
pushwoosh-phonegap-plugin not working with capacitor

### ISSUE THREAD

**Issue by chintan13** [ionic-team/capacitor#973]
I have tried to add this plugin in latest capacitor

"@capacitor/cli": "^1.0.0-beta.8",
"@capacitor/core": "^1.0.0-beta.8",
"@capacitor/ios": "^1.0.0-beta.8",

It gives error as below 

`✖ update ios: Cannot read property 'target' of undefined
[error] TypeError: Cannot read property 'target' of undefined
    at /Volumes/Projects/ionicDemos/PushWooshDemo/node_modules/@capacitor/cli/dist/cordova.js:132:93
    at Array.filter (<anonymous>)
    at cordovaPlugins.map.p (/Volumes/Projects/ionicDemos/PushWooshDemo/node_modules/@capacitor/cli/dist/cordova.js:132:54)
    at Array.map (<anonymous>)
    at autoGenerateConfig (/Volumes/Projects/ionicDemos/PushWooshDemo/node_modules/@capacitor/cli/dist/cordova.js:127:20)
    at Object.handleCordovaPluginsJS (/Volumes/Projects/ionicDemos/PushWooshDemo/node_modules/@capacitor/cli/dist/cordova.js:170:11)
    at <anonymous>`

**Comment by chintan13** [comment]
It still gives error when I try to build it in ios

ld: library not found for -lPushwoosh
clang: error: linker command failed with exit code 1 (use -v to see invocation)

can you help/guide to hot fix it?
